// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsWtsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashWtsMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsWtsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsWtsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsWtsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsWtsMessages(lhsKey, rhsKey) {
          if deepEqualsWtsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsWtsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashWtsMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashWtsMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashWtsMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashWtsMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashWtsMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashWtsMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum WtsValueKind: Int {
  case string = 0
  case number = 1
  case boolean = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsParameterData: Hashable {
  var key: String
  var kind: WtsValueKind
  var stringValue: String? = nil
  var numberValue: Double? = nil
  var booleanValue: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsParameterData? {
    let key = pigeonVar_list[0] as! String
    let kind = pigeonVar_list[1] as! WtsValueKind
    let stringValue: String? = nilOrValue(pigeonVar_list[2])
    let numberValue: Double? = nilOrValue(pigeonVar_list[3])
    let booleanValue: Bool? = nilOrValue(pigeonVar_list[4])

    return WtsParameterData(
      key: key,
      kind: kind,
      stringValue: stringValue,
      numberValue: numberValue,
      booleanValue: booleanValue
    )
  }
  func toList() -> [Any?] {
    return [
      key,
      kind,
      stringValue,
      numberValue,
      booleanValue,
    ]
  }
  static func == (lhs: WtsParameterData, rhs: WtsParameterData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.key, rhs.key) && deepEqualsWtsMessages(lhs.kind, rhs.kind) && deepEqualsWtsMessages(lhs.stringValue, rhs.stringValue) && deepEqualsWtsMessages(lhs.numberValue, rhs.numberValue) && deepEqualsWtsMessages(lhs.booleanValue, rhs.booleanValue)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsParameterData")
    deepHashWtsMessages(value: key, hasher: &hasher)
    deepHashWtsMessages(value: kind, hasher: &hasher)
    deepHashWtsMessages(value: stringValue, hasher: &hasher)
    deepHashWtsMessages(value: numberValue, hasher: &hasher)
    deepHashWtsMessages(value: booleanValue, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsDeepLinkData: Hashable {
  var path: String
  var parameters: [WtsParameterData]
  var linkId: String
  var attributionId: String
  var isDeferred: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsDeepLinkData? {
    let path = pigeonVar_list[0] as! String
    let parameters = pigeonVar_list[1] as! [WtsParameterData]
    let linkId = pigeonVar_list[2] as! String
    let attributionId = pigeonVar_list[3] as! String
    let isDeferred = pigeonVar_list[4] as! Bool

    return WtsDeepLinkData(
      path: path,
      parameters: parameters,
      linkId: linkId,
      attributionId: attributionId,
      isDeferred: isDeferred
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      parameters,
      linkId,
      attributionId,
      isDeferred,
    ]
  }
  static func == (lhs: WtsDeepLinkData, rhs: WtsDeepLinkData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.path, rhs.path) && deepEqualsWtsMessages(lhs.parameters, rhs.parameters) && deepEqualsWtsMessages(lhs.linkId, rhs.linkId) && deepEqualsWtsMessages(lhs.attributionId, rhs.attributionId) && deepEqualsWtsMessages(lhs.isDeferred, rhs.isDeferred)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsDeepLinkData")
    deepHashWtsMessages(value: path, hasher: &hasher)
    deepHashWtsMessages(value: parameters, hasher: &hasher)
    deepHashWtsMessages(value: linkId, hasher: &hasher)
    deepHashWtsMessages(value: attributionId, hasher: &hasher)
    deepHashWtsMessages(value: isDeferred, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsRevenueData: Hashable {
  var amount: String
  var currency: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsRevenueData? {
    let amount = pigeonVar_list[0] as! String
    let currency = pigeonVar_list[1] as! String

    return WtsRevenueData(
      amount: amount,
      currency: currency
    )
  }
  func toList() -> [Any?] {
    return [
      amount,
      currency,
    ]
  }
  static func == (lhs: WtsRevenueData, rhs: WtsRevenueData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.amount, rhs.amount) && deepEqualsWtsMessages(lhs.currency, rhs.currency)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsRevenueData")
    deepHashWtsMessages(value: amount, hasher: &hasher)
    deepHashWtsMessages(value: currency, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsConfigurationData: Hashable {
  var appKey: String
  var apiBaseUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsConfigurationData? {
    let appKey = pigeonVar_list[0] as! String
    let apiBaseUrl: String? = nilOrValue(pigeonVar_list[1])

    return WtsConfigurationData(
      appKey: appKey,
      apiBaseUrl: apiBaseUrl
    )
  }
  func toList() -> [Any?] {
    return [
      appKey,
      apiBaseUrl,
    ]
  }
  static func == (lhs: WtsConfigurationData, rhs: WtsConfigurationData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.appKey, rhs.appKey) && deepEqualsWtsMessages(lhs.apiBaseUrl, rhs.apiBaseUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsConfigurationData")
    deepHashWtsMessages(value: appKey, hasher: &hasher)
    deepHashWtsMessages(value: apiBaseUrl, hasher: &hasher)
  }
}

private class WtsMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WtsValueKind(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return WtsParameterData.fromList(self.readValue() as! [Any?])
    case 131:
      return WtsDeepLinkData.fromList(self.readValue() as! [Any?])
    case 132:
      return WtsRevenueData.fromList(self.readValue() as! [Any?])
    case 133:
      return WtsConfigurationData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class WtsMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? WtsValueKind {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? WtsParameterData {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? WtsDeepLinkData {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? WtsRevenueData {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? WtsConfigurationData {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class WtsMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return WtsMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return WtsMessagesPigeonCodecWriter(data: data)
  }
}

class WtsMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = WtsMessagesPigeonCodec(readerWriter: WtsMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WtsHostApi {
  func configure(configuration: WtsConfigurationData, completion: @escaping (Result<Void, Error>) -> Void)
  func handle(url: String, completion: @escaping (Result<WtsDeepLinkData, Error>) -> Void)
  func getDeferredDeepLink(completion: @escaping (Result<WtsDeepLinkData?, Error>) -> Void)
  func track(eventKey: String, properties: [WtsParameterData], revenue: WtsRevenueData?, linkId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func flush(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WtsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { WtsMessagesPigeonCodec.shared }
  /// Sets up an instance of `WtsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WtsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationArg = args[0] as! WtsConfigurationData
        api.configure(configuration: configurationArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    let handleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.handle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        api.handle(url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      handleChannel.setMessageHandler(nil)
    }
    let getDeferredDeepLinkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.getDeferredDeepLink\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeferredDeepLinkChannel.setMessageHandler { _, reply in
        api.getDeferredDeepLink { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDeferredDeepLinkChannel.setMessageHandler(nil)
    }
    let trackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.track\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let eventKeyArg = args[0] as! String
        let propertiesArg = args[1] as! [WtsParameterData]
        let revenueArg: WtsRevenueData? = nilOrValue(args[2])
        let linkIdArg: String? = nilOrValue(args[3])
        api.track(eventKey: eventKeyArg, properties: propertiesArg, revenue: revenueArg, linkId: linkIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackChannel.setMessageHandler(nil)
    }
    let flushChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.flush\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      flushChannel.setMessageHandler { _, reply in
        api.flush { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      flushChannel.setMessageHandler(nil)
    }
  }
}
