// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsWtsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashWtsMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsWtsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsWtsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsWtsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsWtsMessages(lhsKey, rhsKey) {
          if deepEqualsWtsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsWtsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashWtsMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashWtsMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashWtsMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashWtsMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashWtsMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashWtsMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum WtsValueKind: Int {
  case string = 0
  case number = 1
  case boolean = 2
  case date = 3
  case stringArray = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsParameterData: Hashable {
  var key: String
  var kind: WtsValueKind
  var stringValue: String? = nil
  var numberValue: Double? = nil
  var booleanValue: Bool? = nil
  var stringArrayValue: [String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsParameterData? {
    let key = pigeonVar_list[0] as! String
    let kind = pigeonVar_list[1] as! WtsValueKind
    let stringValue: String? = nilOrValue(pigeonVar_list[2])
    let numberValue: Double? = nilOrValue(pigeonVar_list[3])
    let booleanValue: Bool? = nilOrValue(pigeonVar_list[4])
    let stringArrayValue: [String]? = nilOrValue(pigeonVar_list[5])

    return WtsParameterData(
      key: key,
      kind: kind,
      stringValue: stringValue,
      numberValue: numberValue,
      booleanValue: booleanValue,
      stringArrayValue: stringArrayValue
    )
  }
  func toList() -> [Any?] {
    return [
      key,
      kind,
      stringValue,
      numberValue,
      booleanValue,
      stringArrayValue,
    ]
  }
  static func == (lhs: WtsParameterData, rhs: WtsParameterData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.key, rhs.key) && deepEqualsWtsMessages(lhs.kind, rhs.kind) && deepEqualsWtsMessages(lhs.stringValue, rhs.stringValue) && deepEqualsWtsMessages(lhs.numberValue, rhs.numberValue) && deepEqualsWtsMessages(lhs.booleanValue, rhs.booleanValue) && deepEqualsWtsMessages(lhs.stringArrayValue, rhs.stringArrayValue)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsParameterData")
    deepHashWtsMessages(value: key, hasher: &hasher)
    deepHashWtsMessages(value: kind, hasher: &hasher)
    deepHashWtsMessages(value: stringValue, hasher: &hasher)
    deepHashWtsMessages(value: numberValue, hasher: &hasher)
    deepHashWtsMessages(value: booleanValue, hasher: &hasher)
    deepHashWtsMessages(value: stringArrayValue, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsUserUpdateData: Hashable {
  var set: [WtsParameterData]
  var setOnce: [WtsParameterData]
  var unset: [String]
  var increment: [WtsIncrementData]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsUserUpdateData? {
    let set = pigeonVar_list[0] as! [WtsParameterData]
    let setOnce = pigeonVar_list[1] as! [WtsParameterData]
    let unset = pigeonVar_list[2] as! [String]
    let increment = pigeonVar_list[3] as! [WtsIncrementData]

    return WtsUserUpdateData(
      set: set,
      setOnce: setOnce,
      unset: unset,
      increment: increment
    )
  }
  func toList() -> [Any?] {
    return [
      set,
      setOnce,
      unset,
      increment,
    ]
  }
  static func == (lhs: WtsUserUpdateData, rhs: WtsUserUpdateData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.set, rhs.set) && deepEqualsWtsMessages(lhs.setOnce, rhs.setOnce) && deepEqualsWtsMessages(lhs.unset, rhs.unset) && deepEqualsWtsMessages(lhs.increment, rhs.increment)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsUserUpdateData")
    deepHashWtsMessages(value: set, hasher: &hasher)
    deepHashWtsMessages(value: setOnce, hasher: &hasher)
    deepHashWtsMessages(value: unset, hasher: &hasher)
    deepHashWtsMessages(value: increment, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsIncrementData: Hashable {
  var key: String
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsIncrementData? {
    let key = pigeonVar_list[0] as! String
    let value = pigeonVar_list[1] as! Double

    return WtsIncrementData(
      key: key,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      key,
      value,
    ]
  }
  static func == (lhs: WtsIncrementData, rhs: WtsIncrementData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.key, rhs.key) && deepEqualsWtsMessages(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsIncrementData")
    deepHashWtsMessages(value: key, hasher: &hasher)
    deepHashWtsMessages(value: value, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsReportedAttributionData: Hashable {
  var source: String
  var medium: String? = nil
  var campaign: String? = nil
  var externalRef: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsReportedAttributionData? {
    let source = pigeonVar_list[0] as! String
    let medium: String? = nilOrValue(pigeonVar_list[1])
    let campaign: String? = nilOrValue(pigeonVar_list[2])
    let externalRef: String? = nilOrValue(pigeonVar_list[3])

    return WtsReportedAttributionData(
      source: source,
      medium: medium,
      campaign: campaign,
      externalRef: externalRef
    )
  }
  func toList() -> [Any?] {
    return [
      source,
      medium,
      campaign,
      externalRef,
    ]
  }
  static func == (lhs: WtsReportedAttributionData, rhs: WtsReportedAttributionData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.source, rhs.source) && deepEqualsWtsMessages(lhs.medium, rhs.medium) && deepEqualsWtsMessages(lhs.campaign, rhs.campaign) && deepEqualsWtsMessages(lhs.externalRef, rhs.externalRef)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsReportedAttributionData")
    deepHashWtsMessages(value: source, hasher: &hasher)
    deepHashWtsMessages(value: medium, hasher: &hasher)
    deepHashWtsMessages(value: campaign, hasher: &hasher)
    deepHashWtsMessages(value: externalRef, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsDeepLinkData: Hashable {
  var path: String
  var parameters: [WtsParameterData]
  var linkId: String
  var attributionId: String
  var isDeferred: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsDeepLinkData? {
    let path = pigeonVar_list[0] as! String
    let parameters = pigeonVar_list[1] as! [WtsParameterData]
    let linkId = pigeonVar_list[2] as! String
    let attributionId = pigeonVar_list[3] as! String
    let isDeferred = pigeonVar_list[4] as! Bool

    return WtsDeepLinkData(
      path: path,
      parameters: parameters,
      linkId: linkId,
      attributionId: attributionId,
      isDeferred: isDeferred
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      parameters,
      linkId,
      attributionId,
      isDeferred,
    ]
  }
  static func == (lhs: WtsDeepLinkData, rhs: WtsDeepLinkData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.path, rhs.path) && deepEqualsWtsMessages(lhs.parameters, rhs.parameters) && deepEqualsWtsMessages(lhs.linkId, rhs.linkId) && deepEqualsWtsMessages(lhs.attributionId, rhs.attributionId) && deepEqualsWtsMessages(lhs.isDeferred, rhs.isDeferred)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsDeepLinkData")
    deepHashWtsMessages(value: path, hasher: &hasher)
    deepHashWtsMessages(value: parameters, hasher: &hasher)
    deepHashWtsMessages(value: linkId, hasher: &hasher)
    deepHashWtsMessages(value: attributionId, hasher: &hasher)
    deepHashWtsMessages(value: isDeferred, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsRevenueData: Hashable {
  var amount: String
  var currency: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsRevenueData? {
    let amount = pigeonVar_list[0] as! String
    let currency = pigeonVar_list[1] as! String

    return WtsRevenueData(
      amount: amount,
      currency: currency
    )
  }
  func toList() -> [Any?] {
    return [
      amount,
      currency,
    ]
  }
  static func == (lhs: WtsRevenueData, rhs: WtsRevenueData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.amount, rhs.amount) && deepEqualsWtsMessages(lhs.currency, rhs.currency)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsRevenueData")
    deepHashWtsMessages(value: amount, hasher: &hasher)
    deepHashWtsMessages(value: currency, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsConfigurationData: Hashable {
  var appKey: String
  var apiBaseUrl: String? = nil
  var collectorBaseUrl: String? = nil
  var experiencesEnabled: Bool
  var experienceRenderMode: String
  var allowedInternalRoutes: [String]
  var allowedCallbackKeys: [String]
  var allowedDeepLinkHosts: [String]
  var allowedDeepLinkSchemes: [String]
  var allowedWebOrigins: [String]
  var manifestVerificationKeys: [WtsManifestVerificationKeyData]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsConfigurationData? {
    let appKey = pigeonVar_list[0] as! String
    let apiBaseUrl: String? = nilOrValue(pigeonVar_list[1])
    let collectorBaseUrl: String? = nilOrValue(pigeonVar_list[2])
    let experiencesEnabled = pigeonVar_list[3] as! Bool
    let experienceRenderMode = pigeonVar_list[4] as! String
    let allowedInternalRoutes = pigeonVar_list[5] as! [String]
    let allowedCallbackKeys = pigeonVar_list[6] as! [String]
    let allowedDeepLinkHosts = pigeonVar_list[7] as! [String]
    let allowedDeepLinkSchemes = pigeonVar_list[8] as! [String]
    let allowedWebOrigins = pigeonVar_list[9] as! [String]
    let manifestVerificationKeys = pigeonVar_list[10] as! [WtsManifestVerificationKeyData]

    return WtsConfigurationData(
      appKey: appKey,
      apiBaseUrl: apiBaseUrl,
      collectorBaseUrl: collectorBaseUrl,
      experiencesEnabled: experiencesEnabled,
      experienceRenderMode: experienceRenderMode,
      allowedInternalRoutes: allowedInternalRoutes,
      allowedCallbackKeys: allowedCallbackKeys,
      allowedDeepLinkHosts: allowedDeepLinkHosts,
      allowedDeepLinkSchemes: allowedDeepLinkSchemes,
      allowedWebOrigins: allowedWebOrigins,
      manifestVerificationKeys: manifestVerificationKeys
    )
  }
  func toList() -> [Any?] {
    return [
      appKey,
      apiBaseUrl,
      collectorBaseUrl,
      experiencesEnabled,
      experienceRenderMode,
      allowedInternalRoutes,
      allowedCallbackKeys,
      allowedDeepLinkHosts,
      allowedDeepLinkSchemes,
      allowedWebOrigins,
      manifestVerificationKeys,
    ]
  }
  static func == (lhs: WtsConfigurationData, rhs: WtsConfigurationData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.appKey, rhs.appKey) && deepEqualsWtsMessages(lhs.apiBaseUrl, rhs.apiBaseUrl) && deepEqualsWtsMessages(lhs.collectorBaseUrl, rhs.collectorBaseUrl) && deepEqualsWtsMessages(lhs.experiencesEnabled, rhs.experiencesEnabled) && deepEqualsWtsMessages(lhs.experienceRenderMode, rhs.experienceRenderMode) && deepEqualsWtsMessages(lhs.allowedInternalRoutes, rhs.allowedInternalRoutes) && deepEqualsWtsMessages(lhs.allowedCallbackKeys, rhs.allowedCallbackKeys) && deepEqualsWtsMessages(lhs.allowedDeepLinkHosts, rhs.allowedDeepLinkHosts) && deepEqualsWtsMessages(lhs.allowedDeepLinkSchemes, rhs.allowedDeepLinkSchemes) && deepEqualsWtsMessages(lhs.allowedWebOrigins, rhs.allowedWebOrigins) && deepEqualsWtsMessages(lhs.manifestVerificationKeys, rhs.manifestVerificationKeys)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsConfigurationData")
    deepHashWtsMessages(value: appKey, hasher: &hasher)
    deepHashWtsMessages(value: apiBaseUrl, hasher: &hasher)
    deepHashWtsMessages(value: collectorBaseUrl, hasher: &hasher)
    deepHashWtsMessages(value: experiencesEnabled, hasher: &hasher)
    deepHashWtsMessages(value: experienceRenderMode, hasher: &hasher)
    deepHashWtsMessages(value: allowedInternalRoutes, hasher: &hasher)
    deepHashWtsMessages(value: allowedCallbackKeys, hasher: &hasher)
    deepHashWtsMessages(value: allowedDeepLinkHosts, hasher: &hasher)
    deepHashWtsMessages(value: allowedDeepLinkSchemes, hasher: &hasher)
    deepHashWtsMessages(value: allowedWebOrigins, hasher: &hasher)
    deepHashWtsMessages(value: manifestVerificationKeys, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsManifestVerificationKeyData: Hashable {
  var kid: String
  var value: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsManifestVerificationKeyData? {
    let kid = pigeonVar_list[0] as! String
    let value = pigeonVar_list[1] as! String

    return WtsManifestVerificationKeyData(
      kid: kid,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      kid,
      value,
    ]
  }
  static func == (lhs: WtsManifestVerificationKeyData, rhs: WtsManifestVerificationKeyData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.kid, rhs.kid) && deepEqualsWtsMessages(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsManifestVerificationKeyData")
    deepHashWtsMessages(value: kid, hasher: &hasher)
    deepHashWtsMessages(value: value, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsExperienceDiagnosticsData: Hashable {
  var enabled: Bool
  var consent: String
  var queued: Int64
  var presenting: Bool
  var testDeviceToken: String
  var lastErrorCode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsExperienceDiagnosticsData? {
    let enabled = pigeonVar_list[0] as! Bool
    let consent = pigeonVar_list[1] as! String
    let queued = pigeonVar_list[2] as! Int64
    let presenting = pigeonVar_list[3] as! Bool
    let testDeviceToken = pigeonVar_list[4] as! String
    let lastErrorCode: String? = nilOrValue(pigeonVar_list[5])

    return WtsExperienceDiagnosticsData(
      enabled: enabled,
      consent: consent,
      queued: queued,
      presenting: presenting,
      testDeviceToken: testDeviceToken,
      lastErrorCode: lastErrorCode
    )
  }
  func toList() -> [Any?] {
    return [
      enabled,
      consent,
      queued,
      presenting,
      testDeviceToken,
      lastErrorCode,
    ]
  }
  static func == (lhs: WtsExperienceDiagnosticsData, rhs: WtsExperienceDiagnosticsData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.enabled, rhs.enabled) && deepEqualsWtsMessages(lhs.consent, rhs.consent) && deepEqualsWtsMessages(lhs.queued, rhs.queued) && deepEqualsWtsMessages(lhs.presenting, rhs.presenting) && deepEqualsWtsMessages(lhs.testDeviceToken, rhs.testDeviceToken) && deepEqualsWtsMessages(lhs.lastErrorCode, rhs.lastErrorCode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsExperienceDiagnosticsData")
    deepHashWtsMessages(value: enabled, hasher: &hasher)
    deepHashWtsMessages(value: consent, hasher: &hasher)
    deepHashWtsMessages(value: queued, hasher: &hasher)
    deepHashWtsMessages(value: presenting, hasher: &hasher)
    deepHashWtsMessages(value: testDeviceToken, hasher: &hasher)
    deepHashWtsMessages(value: lastErrorCode, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsExperienceActionData: Hashable {
  var id: String
  var label: String
  var type: String
  var target: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsExperienceActionData? {
    let id = pigeonVar_list[0] as! String
    let label = pigeonVar_list[1] as! String
    let type = pigeonVar_list[2] as! String
    let target: String? = nilOrValue(pigeonVar_list[3])

    return WtsExperienceActionData(
      id: id,
      label: label,
      type: type,
      target: target
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      label,
      type,
      target,
    ]
  }
  static func == (lhs: WtsExperienceActionData, rhs: WtsExperienceActionData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.id, rhs.id) && deepEqualsWtsMessages(lhs.label, rhs.label) && deepEqualsWtsMessages(lhs.type, rhs.type) && deepEqualsWtsMessages(lhs.target, rhs.target)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsExperienceActionData")
    deepHashWtsMessages(value: id, hasher: &hasher)
    deepHashWtsMessages(value: label, hasher: &hasher)
    deepHashWtsMessages(value: type, hasher: &hasher)
    deepHashWtsMessages(value: target, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsExperienceTranslationData: Hashable {
  var locale: String
  var title: String
  var description: String
  var primaryAction: WtsExperienceActionData? = nil
  var secondaryAction: WtsExperienceActionData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsExperienceTranslationData? {
    let locale = pigeonVar_list[0] as! String
    let title = pigeonVar_list[1] as! String
    let description = pigeonVar_list[2] as! String
    let primaryAction: WtsExperienceActionData? = nilOrValue(pigeonVar_list[3])
    let secondaryAction: WtsExperienceActionData? = nilOrValue(pigeonVar_list[4])

    return WtsExperienceTranslationData(
      locale: locale,
      title: title,
      description: description,
      primaryAction: primaryAction,
      secondaryAction: secondaryAction
    )
  }
  func toList() -> [Any?] {
    return [
      locale,
      title,
      description,
      primaryAction,
      secondaryAction,
    ]
  }
  static func == (lhs: WtsExperienceTranslationData, rhs: WtsExperienceTranslationData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.locale, rhs.locale) && deepEqualsWtsMessages(lhs.title, rhs.title) && deepEqualsWtsMessages(lhs.description, rhs.description) && deepEqualsWtsMessages(lhs.primaryAction, rhs.primaryAction) && deepEqualsWtsMessages(lhs.secondaryAction, rhs.secondaryAction)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsExperienceTranslationData")
    deepHashWtsMessages(value: locale, hasher: &hasher)
    deepHashWtsMessages(value: title, hasher: &hasher)
    deepHashWtsMessages(value: description, hasher: &hasher)
    deepHashWtsMessages(value: primaryAction, hasher: &hasher)
    deepHashWtsMessages(value: secondaryAction, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsExperienceData: Hashable {
  var campaignId: String
  var campaignVersionId: String
  var assignmentId: String
  var variantId: String
  var exposureId: String
  var placement: String
  var priority: Int64
  var translations: [WtsExperienceTranslationData]
  var closeable: Bool
  var themePreset: String
  var delaySeconds: Double
  var autoCloseSeconds: Double? = nil
  var assetUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsExperienceData? {
    let campaignId = pigeonVar_list[0] as! String
    let campaignVersionId = pigeonVar_list[1] as! String
    let assignmentId = pigeonVar_list[2] as! String
    let variantId = pigeonVar_list[3] as! String
    let exposureId = pigeonVar_list[4] as! String
    let placement = pigeonVar_list[5] as! String
    let priority = pigeonVar_list[6] as! Int64
    let translations = pigeonVar_list[7] as! [WtsExperienceTranslationData]
    let closeable = pigeonVar_list[8] as! Bool
    let themePreset = pigeonVar_list[9] as! String
    let delaySeconds = pigeonVar_list[10] as! Double
    let autoCloseSeconds: Double? = nilOrValue(pigeonVar_list[11])
    let assetUrl: String? = nilOrValue(pigeonVar_list[12])

    return WtsExperienceData(
      campaignId: campaignId,
      campaignVersionId: campaignVersionId,
      assignmentId: assignmentId,
      variantId: variantId,
      exposureId: exposureId,
      placement: placement,
      priority: priority,
      translations: translations,
      closeable: closeable,
      themePreset: themePreset,
      delaySeconds: delaySeconds,
      autoCloseSeconds: autoCloseSeconds,
      assetUrl: assetUrl
    )
  }
  func toList() -> [Any?] {
    return [
      campaignId,
      campaignVersionId,
      assignmentId,
      variantId,
      exposureId,
      placement,
      priority,
      translations,
      closeable,
      themePreset,
      delaySeconds,
      autoCloseSeconds,
      assetUrl,
    ]
  }
  static func == (lhs: WtsExperienceData, rhs: WtsExperienceData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.campaignId, rhs.campaignId) && deepEqualsWtsMessages(lhs.campaignVersionId, rhs.campaignVersionId) && deepEqualsWtsMessages(lhs.assignmentId, rhs.assignmentId) && deepEqualsWtsMessages(lhs.variantId, rhs.variantId) && deepEqualsWtsMessages(lhs.exposureId, rhs.exposureId) && deepEqualsWtsMessages(lhs.placement, rhs.placement) && deepEqualsWtsMessages(lhs.priority, rhs.priority) && deepEqualsWtsMessages(lhs.translations, rhs.translations) && deepEqualsWtsMessages(lhs.closeable, rhs.closeable) && deepEqualsWtsMessages(lhs.themePreset, rhs.themePreset) && deepEqualsWtsMessages(lhs.delaySeconds, rhs.delaySeconds) && deepEqualsWtsMessages(lhs.autoCloseSeconds, rhs.autoCloseSeconds) && deepEqualsWtsMessages(lhs.assetUrl, rhs.assetUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsExperienceData")
    deepHashWtsMessages(value: campaignId, hasher: &hasher)
    deepHashWtsMessages(value: campaignVersionId, hasher: &hasher)
    deepHashWtsMessages(value: assignmentId, hasher: &hasher)
    deepHashWtsMessages(value: variantId, hasher: &hasher)
    deepHashWtsMessages(value: exposureId, hasher: &hasher)
    deepHashWtsMessages(value: placement, hasher: &hasher)
    deepHashWtsMessages(value: priority, hasher: &hasher)
    deepHashWtsMessages(value: translations, hasher: &hasher)
    deepHashWtsMessages(value: closeable, hasher: &hasher)
    deepHashWtsMessages(value: themePreset, hasher: &hasher)
    deepHashWtsMessages(value: delaySeconds, hasher: &hasher)
    deepHashWtsMessages(value: autoCloseSeconds, hasher: &hasher)
    deepHashWtsMessages(value: assetUrl, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsExperiencePresentationHandleData: Hashable {
  var exposureId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsExperiencePresentationHandleData? {
    let exposureId = pigeonVar_list[0] as! String

    return WtsExperiencePresentationHandleData(
      exposureId: exposureId
    )
  }
  func toList() -> [Any?] {
    return [
      exposureId
    ]
  }
  static func == (lhs: WtsExperiencePresentationHandleData, rhs: WtsExperiencePresentationHandleData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.exposureId, rhs.exposureId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsExperiencePresentationHandleData")
    deepHashWtsMessages(value: exposureId, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsExperienceManualPresentationData: Hashable {
  var experience: WtsExperienceData
  var handle: WtsExperiencePresentationHandleData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsExperienceManualPresentationData? {
    let experience = pigeonVar_list[0] as! WtsExperienceData
    let handle = pigeonVar_list[1] as! WtsExperiencePresentationHandleData

    return WtsExperienceManualPresentationData(
      experience: experience,
      handle: handle
    )
  }
  func toList() -> [Any?] {
    return [
      experience,
      handle,
    ]
  }
  static func == (lhs: WtsExperienceManualPresentationData, rhs: WtsExperienceManualPresentationData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.experience, rhs.experience) && deepEqualsWtsMessages(lhs.handle, rhs.handle)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsExperienceManualPresentationData")
    deepHashWtsMessages(value: experience, hasher: &hasher)
    deepHashWtsMessages(value: handle, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsExperienceLifecycleOutcomeData: Hashable {
  var accepted: Bool
  var idempotent: Bool
  var code: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsExperienceLifecycleOutcomeData? {
    let accepted = pigeonVar_list[0] as! Bool
    let idempotent = pigeonVar_list[1] as! Bool
    let code: String? = nilOrValue(pigeonVar_list[2])

    return WtsExperienceLifecycleOutcomeData(
      accepted: accepted,
      idempotent: idempotent,
      code: code
    )
  }
  func toList() -> [Any?] {
    return [
      accepted,
      idempotent,
      code,
    ]
  }
  static func == (lhs: WtsExperienceLifecycleOutcomeData, rhs: WtsExperienceLifecycleOutcomeData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.accepted, rhs.accepted) && deepEqualsWtsMessages(lhs.idempotent, rhs.idempotent) && deepEqualsWtsMessages(lhs.code, rhs.code)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsExperienceLifecycleOutcomeData")
    deepHashWtsMessages(value: accepted, hasher: &hasher)
    deepHashWtsMessages(value: idempotent, hasher: &hasher)
    deepHashWtsMessages(value: code, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsTestSessionCheckData: Hashable {
  var key: String
  var status: String
  var code: String? = nil
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsTestSessionCheckData? {
    let key = pigeonVar_list[0] as! String
    let status = pigeonVar_list[1] as! String
    let code: String? = nilOrValue(pigeonVar_list[2])
    let message: String? = nilOrValue(pigeonVar_list[3])

    return WtsTestSessionCheckData(
      key: key,
      status: status,
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      key,
      status,
      code,
      message,
    ]
  }
  static func == (lhs: WtsTestSessionCheckData, rhs: WtsTestSessionCheckData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.key, rhs.key) && deepEqualsWtsMessages(lhs.status, rhs.status) && deepEqualsWtsMessages(lhs.code, rhs.code) && deepEqualsWtsMessages(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsTestSessionCheckData")
    deepHashWtsMessages(value: key, hasher: &hasher)
    deepHashWtsMessages(value: status, hasher: &hasher)
    deepHashWtsMessages(value: code, hasher: &hasher)
    deepHashWtsMessages(value: message, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsTestSessionJoinData: Hashable {
  var accepted: Bool
  var joined: Bool
  var compatible: Bool
  var checks: [WtsTestSessionCheckData]
  var requiredSdkVersion: String? = nil
  var sessionId: String? = nil
  var expiresAt: String? = nil
  var testProfileExternalUserId: String? = nil
  var errorCode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsTestSessionJoinData? {
    let accepted = pigeonVar_list[0] as! Bool
    let joined = pigeonVar_list[1] as! Bool
    let compatible = pigeonVar_list[2] as! Bool
    let checks = pigeonVar_list[3] as! [WtsTestSessionCheckData]
    let requiredSdkVersion: String? = nilOrValue(pigeonVar_list[4])
    let sessionId: String? = nilOrValue(pigeonVar_list[5])
    let expiresAt: String? = nilOrValue(pigeonVar_list[6])
    let testProfileExternalUserId: String? = nilOrValue(pigeonVar_list[7])
    let errorCode: String? = nilOrValue(pigeonVar_list[8])

    return WtsTestSessionJoinData(
      accepted: accepted,
      joined: joined,
      compatible: compatible,
      checks: checks,
      requiredSdkVersion: requiredSdkVersion,
      sessionId: sessionId,
      expiresAt: expiresAt,
      testProfileExternalUserId: testProfileExternalUserId,
      errorCode: errorCode
    )
  }
  func toList() -> [Any?] {
    return [
      accepted,
      joined,
      compatible,
      checks,
      requiredSdkVersion,
      sessionId,
      expiresAt,
      testProfileExternalUserId,
      errorCode,
    ]
  }
  static func == (lhs: WtsTestSessionJoinData, rhs: WtsTestSessionJoinData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.accepted, rhs.accepted) && deepEqualsWtsMessages(lhs.joined, rhs.joined) && deepEqualsWtsMessages(lhs.compatible, rhs.compatible) && deepEqualsWtsMessages(lhs.checks, rhs.checks) && deepEqualsWtsMessages(lhs.requiredSdkVersion, rhs.requiredSdkVersion) && deepEqualsWtsMessages(lhs.sessionId, rhs.sessionId) && deepEqualsWtsMessages(lhs.expiresAt, rhs.expiresAt) && deepEqualsWtsMessages(lhs.testProfileExternalUserId, rhs.testProfileExternalUserId) && deepEqualsWtsMessages(lhs.errorCode, rhs.errorCode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsTestSessionJoinData")
    deepHashWtsMessages(value: accepted, hasher: &hasher)
    deepHashWtsMessages(value: joined, hasher: &hasher)
    deepHashWtsMessages(value: compatible, hasher: &hasher)
    deepHashWtsMessages(value: checks, hasher: &hasher)
    deepHashWtsMessages(value: requiredSdkVersion, hasher: &hasher)
    deepHashWtsMessages(value: sessionId, hasher: &hasher)
    deepHashWtsMessages(value: expiresAt, hasher: &hasher)
    deepHashWtsMessages(value: testProfileExternalUserId, hasher: &hasher)
    deepHashWtsMessages(value: errorCode, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsTestSessionDiagnosticsData: Hashable {
  var joined: Bool
  var compatible: Bool
  var checks: [WtsTestSessionCheckData]
  var pendingSignals: Int64
  var sessionId: String? = nil
  var expiresAt: String? = nil
  var requiredSdkVersion: String? = nil
  var lastErrorCode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsTestSessionDiagnosticsData? {
    let joined = pigeonVar_list[0] as! Bool
    let compatible = pigeonVar_list[1] as! Bool
    let checks = pigeonVar_list[2] as! [WtsTestSessionCheckData]
    let pendingSignals = pigeonVar_list[3] as! Int64
    let sessionId: String? = nilOrValue(pigeonVar_list[4])
    let expiresAt: String? = nilOrValue(pigeonVar_list[5])
    let requiredSdkVersion: String? = nilOrValue(pigeonVar_list[6])
    let lastErrorCode: String? = nilOrValue(pigeonVar_list[7])

    return WtsTestSessionDiagnosticsData(
      joined: joined,
      compatible: compatible,
      checks: checks,
      pendingSignals: pendingSignals,
      sessionId: sessionId,
      expiresAt: expiresAt,
      requiredSdkVersion: requiredSdkVersion,
      lastErrorCode: lastErrorCode
    )
  }
  func toList() -> [Any?] {
    return [
      joined,
      compatible,
      checks,
      pendingSignals,
      sessionId,
      expiresAt,
      requiredSdkVersion,
      lastErrorCode,
    ]
  }
  static func == (lhs: WtsTestSessionDiagnosticsData, rhs: WtsTestSessionDiagnosticsData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.joined, rhs.joined) && deepEqualsWtsMessages(lhs.compatible, rhs.compatible) && deepEqualsWtsMessages(lhs.checks, rhs.checks) && deepEqualsWtsMessages(lhs.pendingSignals, rhs.pendingSignals) && deepEqualsWtsMessages(lhs.sessionId, rhs.sessionId) && deepEqualsWtsMessages(lhs.expiresAt, rhs.expiresAt) && deepEqualsWtsMessages(lhs.requiredSdkVersion, rhs.requiredSdkVersion) && deepEqualsWtsMessages(lhs.lastErrorCode, rhs.lastErrorCode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsTestSessionDiagnosticsData")
    deepHashWtsMessages(value: joined, hasher: &hasher)
    deepHashWtsMessages(value: compatible, hasher: &hasher)
    deepHashWtsMessages(value: checks, hasher: &hasher)
    deepHashWtsMessages(value: pendingSignals, hasher: &hasher)
    deepHashWtsMessages(value: sessionId, hasher: &hasher)
    deepHashWtsMessages(value: expiresAt, hasher: &hasher)
    deepHashWtsMessages(value: requiredSdkVersion, hasher: &hasher)
    deepHashWtsMessages(value: lastErrorCode, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsTestSessionProbeLinkData: Hashable {
  var id: String
  var path: String
  var parametersJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsTestSessionProbeLinkData? {
    let id = pigeonVar_list[0] as! String
    let path = pigeonVar_list[1] as! String
    let parametersJson = pigeonVar_list[2] as! String

    return WtsTestSessionProbeLinkData(
      id: id,
      path: path,
      parametersJson: parametersJson
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      path,
      parametersJson,
    ]
  }
  static func == (lhs: WtsTestSessionProbeLinkData, rhs: WtsTestSessionProbeLinkData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.id, rhs.id) && deepEqualsWtsMessages(lhs.path, rhs.path) && deepEqualsWtsMessages(lhs.parametersJson, rhs.parametersJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsTestSessionProbeLinkData")
    deepHashWtsMessages(value: id, hasher: &hasher)
    deepHashWtsMessages(value: path, hasher: &hasher)
    deepHashWtsMessages(value: parametersJson, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsTestSessionProbeData: Hashable {
  var match: Bool
  var status: String
  var code: String
  var originalUrl: String
  var fallbackUrl: String
  var link: WtsTestSessionProbeLinkData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsTestSessionProbeData? {
    let match = pigeonVar_list[0] as! Bool
    let status = pigeonVar_list[1] as! String
    let code = pigeonVar_list[2] as! String
    let originalUrl = pigeonVar_list[3] as! String
    let fallbackUrl = pigeonVar_list[4] as! String
    let link: WtsTestSessionProbeLinkData? = nilOrValue(pigeonVar_list[5])

    return WtsTestSessionProbeData(
      match: match,
      status: status,
      code: code,
      originalUrl: originalUrl,
      fallbackUrl: fallbackUrl,
      link: link
    )
  }
  func toList() -> [Any?] {
    return [
      match,
      status,
      code,
      originalUrl,
      fallbackUrl,
      link,
    ]
  }
  static func == (lhs: WtsTestSessionProbeData, rhs: WtsTestSessionProbeData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.match, rhs.match) && deepEqualsWtsMessages(lhs.status, rhs.status) && deepEqualsWtsMessages(lhs.code, rhs.code) && deepEqualsWtsMessages(lhs.originalUrl, rhs.originalUrl) && deepEqualsWtsMessages(lhs.fallbackUrl, rhs.fallbackUrl) && deepEqualsWtsMessages(lhs.link, rhs.link)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsTestSessionProbeData")
    deepHashWtsMessages(value: match, hasher: &hasher)
    deepHashWtsMessages(value: status, hasher: &hasher)
    deepHashWtsMessages(value: code, hasher: &hasher)
    deepHashWtsMessages(value: originalUrl, hasher: &hasher)
    deepHashWtsMessages(value: fallbackUrl, hasher: &hasher)
    deepHashWtsMessages(value: link, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WtsTestSessionProbeRunData: Hashable {
  var accepted: Bool
  var emitted: [String]
  var skipped: [String]
  var pendingSignals: Int64
  var experienceDecisionJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WtsTestSessionProbeRunData? {
    let accepted = pigeonVar_list[0] as! Bool
    let emitted = pigeonVar_list[1] as! [String]
    let skipped = pigeonVar_list[2] as! [String]
    let pendingSignals = pigeonVar_list[3] as! Int64
    let experienceDecisionJson: String? = nilOrValue(pigeonVar_list[4])

    return WtsTestSessionProbeRunData(
      accepted: accepted,
      emitted: emitted,
      skipped: skipped,
      pendingSignals: pendingSignals,
      experienceDecisionJson: experienceDecisionJson
    )
  }
  func toList() -> [Any?] {
    return [
      accepted,
      emitted,
      skipped,
      pendingSignals,
      experienceDecisionJson,
    ]
  }
  static func == (lhs: WtsTestSessionProbeRunData, rhs: WtsTestSessionProbeRunData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWtsMessages(lhs.accepted, rhs.accepted) && deepEqualsWtsMessages(lhs.emitted, rhs.emitted) && deepEqualsWtsMessages(lhs.skipped, rhs.skipped) && deepEqualsWtsMessages(lhs.pendingSignals, rhs.pendingSignals) && deepEqualsWtsMessages(lhs.experienceDecisionJson, rhs.experienceDecisionJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WtsTestSessionProbeRunData")
    deepHashWtsMessages(value: accepted, hasher: &hasher)
    deepHashWtsMessages(value: emitted, hasher: &hasher)
    deepHashWtsMessages(value: skipped, hasher: &hasher)
    deepHashWtsMessages(value: pendingSignals, hasher: &hasher)
    deepHashWtsMessages(value: experienceDecisionJson, hasher: &hasher)
  }
}

private class WtsMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WtsValueKind(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return WtsParameterData.fromList(self.readValue() as! [Any?])
    case 131:
      return WtsUserUpdateData.fromList(self.readValue() as! [Any?])
    case 132:
      return WtsIncrementData.fromList(self.readValue() as! [Any?])
    case 133:
      return WtsReportedAttributionData.fromList(self.readValue() as! [Any?])
    case 134:
      return WtsDeepLinkData.fromList(self.readValue() as! [Any?])
    case 135:
      return WtsRevenueData.fromList(self.readValue() as! [Any?])
    case 136:
      return WtsConfigurationData.fromList(self.readValue() as! [Any?])
    case 137:
      return WtsManifestVerificationKeyData.fromList(self.readValue() as! [Any?])
    case 138:
      return WtsExperienceDiagnosticsData.fromList(self.readValue() as! [Any?])
    case 139:
      return WtsExperienceActionData.fromList(self.readValue() as! [Any?])
    case 140:
      return WtsExperienceTranslationData.fromList(self.readValue() as! [Any?])
    case 141:
      return WtsExperienceData.fromList(self.readValue() as! [Any?])
    case 142:
      return WtsExperiencePresentationHandleData.fromList(self.readValue() as! [Any?])
    case 143:
      return WtsExperienceManualPresentationData.fromList(self.readValue() as! [Any?])
    case 144:
      return WtsExperienceLifecycleOutcomeData.fromList(self.readValue() as! [Any?])
    case 145:
      return WtsTestSessionCheckData.fromList(self.readValue() as! [Any?])
    case 146:
      return WtsTestSessionJoinData.fromList(self.readValue() as! [Any?])
    case 147:
      return WtsTestSessionDiagnosticsData.fromList(self.readValue() as! [Any?])
    case 148:
      return WtsTestSessionProbeLinkData.fromList(self.readValue() as! [Any?])
    case 149:
      return WtsTestSessionProbeData.fromList(self.readValue() as! [Any?])
    case 150:
      return WtsTestSessionProbeRunData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class WtsMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? WtsValueKind {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? WtsParameterData {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? WtsUserUpdateData {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? WtsIncrementData {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? WtsReportedAttributionData {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? WtsDeepLinkData {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? WtsRevenueData {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? WtsConfigurationData {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? WtsManifestVerificationKeyData {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? WtsExperienceDiagnosticsData {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? WtsExperienceActionData {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? WtsExperienceTranslationData {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? WtsExperienceData {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? WtsExperiencePresentationHandleData {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? WtsExperienceManualPresentationData {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? WtsExperienceLifecycleOutcomeData {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? WtsTestSessionCheckData {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? WtsTestSessionJoinData {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? WtsTestSessionDiagnosticsData {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? WtsTestSessionProbeLinkData {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? WtsTestSessionProbeData {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? WtsTestSessionProbeRunData {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class WtsMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return WtsMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return WtsMessagesPigeonCodecWriter(data: data)
  }
}

class WtsMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = WtsMessagesPigeonCodec(readerWriter: WtsMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol WtsFlutterApiProtocol {
  func onExperienceAvailable(presentation presentationArg: WtsExperienceManualPresentationData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onExperienceAction(experience experienceArg: WtsExperienceData, action actionArg: WtsExperienceActionData, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class WtsFlutterApi: WtsFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: WtsMessagesPigeonCodec {
    return WtsMessagesPigeonCodec.shared
  }
  func onExperienceAvailable(presentation presentationArg: WtsExperienceManualPresentationData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wts_sdk.WtsFlutterApi.onExperienceAvailable\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([presentationArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onExperienceAction(experience experienceArg: WtsExperienceData, action actionArg: WtsExperienceActionData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wts_sdk.WtsFlutterApi.onExperienceAction\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([experienceArg, actionArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WtsHostApi {
  func configure(configuration: WtsConfigurationData, completion: @escaping (Result<Void, Error>) -> Void)
  func handle(url: String, completion: @escaping (Result<WtsDeepLinkData, Error>) -> Void)
  func getDeferredDeepLink(completion: @escaping (Result<WtsDeepLinkData?, Error>) -> Void)
  func setProfileConsent(granted: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func identify(externalUserId: String, attributes: [WtsParameterData], completion: @escaping (Result<Void, Error>) -> Void)
  func updateUser(update: WtsUserUpdateData, completion: @escaping (Result<Void, Error>) -> Void)
  func setReportedAttribution(attribution: WtsReportedAttributionData, completion: @escaping (Result<Void, Error>) -> Void)
  func resetIdentity(completion: @escaping (Result<Void, Error>) -> Void)
  func track(eventKey: String, properties: [WtsParameterData], revenue: WtsRevenueData?, linkId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func screen(name: String, properties: [WtsParameterData], completion: @escaping (Result<Void, Error>) -> Void)
  func setExperienceConsent(consent: String, completion: @escaping (Result<String, Error>) -> Void)
  func presentNextExperience(completion: @escaping (Result<Bool, Error>) -> Void)
  func dismissCurrentExperience(completion: @escaping (Result<Bool, Error>) -> Void)
  func getExperienceDiagnostics(completion: @escaping (Result<WtsExperienceDiagnosticsData, Error>) -> Void)
  func acknowledgeExperienceRender(handle: WtsExperiencePresentationHandleData, completion: @escaping (Result<WtsExperienceLifecycleOutcomeData, Error>) -> Void)
  func acknowledgeExperienceImpression(handle: WtsExperiencePresentationHandleData, completion: @escaping (Result<WtsExperienceLifecycleOutcomeData, Error>) -> Void)
  func reportExperienceAction(handle: WtsExperiencePresentationHandleData, actionId: String, completion: @escaping (Result<WtsExperienceLifecycleOutcomeData, Error>) -> Void)
  func dismissExperience(handle: WtsExperiencePresentationHandleData, reason: String, failureCode: String?, completion: @escaping (Result<WtsExperienceLifecycleOutcomeData, Error>) -> Void)
  func joinTestSession(pairing: String, completion: @escaping (Result<WtsTestSessionJoinData, Error>) -> Void)
  func leaveTestSession(completion: @escaping (Result<Bool, Error>) -> Void)
  func getTestSessionDiagnostics(completion: @escaping (Result<WtsTestSessionDiagnosticsData, Error>) -> Void)
  func probeTestSessionUrl(url: String, completion: @escaping (Result<WtsTestSessionProbeData, Error>) -> Void)
  func runTestSessionProbes(completion: @escaping (Result<WtsTestSessionProbeRunData, Error>) -> Void)
  func reportTestSessionExperienceInteraction(interaction: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func flush(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WtsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { WtsMessagesPigeonCodec.shared }
  /// Sets up an instance of `WtsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WtsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationArg = args[0] as! WtsConfigurationData
        api.configure(configuration: configurationArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    let handleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.handle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        api.handle(url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      handleChannel.setMessageHandler(nil)
    }
    let getDeferredDeepLinkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.getDeferredDeepLink\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeferredDeepLinkChannel.setMessageHandler { _, reply in
        api.getDeferredDeepLink { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDeferredDeepLinkChannel.setMessageHandler(nil)
    }
    let setProfileConsentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.setProfileConsent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setProfileConsentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let grantedArg = args[0] as! Bool
        api.setProfileConsent(granted: grantedArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setProfileConsentChannel.setMessageHandler(nil)
    }
    let identifyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.identify\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      identifyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let externalUserIdArg = args[0] as! String
        let attributesArg = args[1] as! [WtsParameterData]
        api.identify(externalUserId: externalUserIdArg, attributes: attributesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      identifyChannel.setMessageHandler(nil)
    }
    let updateUserChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.updateUser\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateUserChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let updateArg = args[0] as! WtsUserUpdateData
        api.updateUser(update: updateArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateUserChannel.setMessageHandler(nil)
    }
    let setReportedAttributionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.setReportedAttribution\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setReportedAttributionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let attributionArg = args[0] as! WtsReportedAttributionData
        api.setReportedAttribution(attribution: attributionArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setReportedAttributionChannel.setMessageHandler(nil)
    }
    let resetIdentityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.resetIdentity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetIdentityChannel.setMessageHandler { _, reply in
        api.resetIdentity { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      resetIdentityChannel.setMessageHandler(nil)
    }
    let trackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.track\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let eventKeyArg = args[0] as! String
        let propertiesArg = args[1] as! [WtsParameterData]
        let revenueArg: WtsRevenueData? = nilOrValue(args[2])
        let linkIdArg: String? = nilOrValue(args[3])
        api.track(eventKey: eventKeyArg, properties: propertiesArg, revenue: revenueArg, linkId: linkIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackChannel.setMessageHandler(nil)
    }
    let screenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.screen\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      screenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        let propertiesArg = args[1] as! [WtsParameterData]
        api.screen(name: nameArg, properties: propertiesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      screenChannel.setMessageHandler(nil)
    }
    let setExperienceConsentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.setExperienceConsent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setExperienceConsentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let consentArg = args[0] as! String
        api.setExperienceConsent(consent: consentArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setExperienceConsentChannel.setMessageHandler(nil)
    }
    let presentNextExperienceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.presentNextExperience\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      presentNextExperienceChannel.setMessageHandler { _, reply in
        api.presentNextExperience { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      presentNextExperienceChannel.setMessageHandler(nil)
    }
    let dismissCurrentExperienceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.dismissCurrentExperience\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      dismissCurrentExperienceChannel.setMessageHandler { _, reply in
        api.dismissCurrentExperience { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      dismissCurrentExperienceChannel.setMessageHandler(nil)
    }
    let getExperienceDiagnosticsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.getExperienceDiagnostics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getExperienceDiagnosticsChannel.setMessageHandler { _, reply in
        api.getExperienceDiagnostics { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getExperienceDiagnosticsChannel.setMessageHandler(nil)
    }
    let acknowledgeExperienceRenderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.acknowledgeExperienceRender\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      acknowledgeExperienceRenderChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! WtsExperiencePresentationHandleData
        api.acknowledgeExperienceRender(handle: handleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      acknowledgeExperienceRenderChannel.setMessageHandler(nil)
    }
    let acknowledgeExperienceImpressionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.acknowledgeExperienceImpression\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      acknowledgeExperienceImpressionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! WtsExperiencePresentationHandleData
        api.acknowledgeExperienceImpression(handle: handleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      acknowledgeExperienceImpressionChannel.setMessageHandler(nil)
    }
    let reportExperienceActionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.reportExperienceAction\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reportExperienceActionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! WtsExperiencePresentationHandleData
        let actionIdArg = args[1] as! String
        api.reportExperienceAction(handle: handleArg, actionId: actionIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      reportExperienceActionChannel.setMessageHandler(nil)
    }
    let dismissExperienceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.dismissExperience\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      dismissExperienceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! WtsExperiencePresentationHandleData
        let reasonArg = args[1] as! String
        let failureCodeArg: String? = nilOrValue(args[2])
        api.dismissExperience(handle: handleArg, reason: reasonArg, failureCode: failureCodeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      dismissExperienceChannel.setMessageHandler(nil)
    }
    let joinTestSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.joinTestSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      joinTestSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pairingArg = args[0] as! String
        api.joinTestSession(pairing: pairingArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      joinTestSessionChannel.setMessageHandler(nil)
    }
    let leaveTestSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.leaveTestSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      leaveTestSessionChannel.setMessageHandler { _, reply in
        api.leaveTestSession { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      leaveTestSessionChannel.setMessageHandler(nil)
    }
    let getTestSessionDiagnosticsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.getTestSessionDiagnostics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getTestSessionDiagnosticsChannel.setMessageHandler { _, reply in
        api.getTestSessionDiagnostics { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getTestSessionDiagnosticsChannel.setMessageHandler(nil)
    }
    let probeTestSessionUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.probeTestSessionUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      probeTestSessionUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        api.probeTestSessionUrl(url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      probeTestSessionUrlChannel.setMessageHandler(nil)
    }
    let runTestSessionProbesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.runTestSessionProbes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      runTestSessionProbesChannel.setMessageHandler { _, reply in
        api.runTestSessionProbes { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      runTestSessionProbesChannel.setMessageHandler(nil)
    }
    let reportTestSessionExperienceInteractionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.reportTestSessionExperienceInteraction\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reportTestSessionExperienceInteractionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let interactionArg = args[0] as! String
        api.reportTestSessionExperienceInteraction(interaction: interactionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      reportTestSessionExperienceInteractionChannel.setMessageHandler(nil)
    }
    let flushChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wts_sdk.WtsHostApi.flush\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      flushChannel.setMessageHandler { _, reply in
        api.flush { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      flushChannel.setMessageHandler(nil)
    }
  }
}
