// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum WtsValueKind {
  string,
  number,
  boolean,
}

class WtsParameterData {
  WtsParameterData({
    required this.key,
    required this.kind,
    this.stringValue,
    this.numberValue,
    this.booleanValue,
  });

  String key;

  WtsValueKind kind;

  String? stringValue;

  double? numberValue;

  bool? booleanValue;

  List<Object?> _toList() {
    return <Object?>[
      key,
      kind,
      stringValue,
      numberValue,
      booleanValue,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsParameterData decode(Object result) {
    result as List<Object?>;
    return WtsParameterData(
      key: result[0]! as String,
      kind: result[1]! as WtsValueKind,
      stringValue: result[2] as String?,
      numberValue: result[3] as double?,
      booleanValue: result[4] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsParameterData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(key, other.key) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(stringValue, other.stringValue) &&
        _deepEquals(numberValue, other.numberValue) &&
        _deepEquals(booleanValue, other.booleanValue);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsDeepLinkData {
  WtsDeepLinkData({
    required this.path,
    required this.parameters,
    required this.linkId,
    required this.attributionId,
    required this.isDeferred,
  });

  String path;

  List<WtsParameterData> parameters;

  String linkId;

  String attributionId;

  bool isDeferred;

  List<Object?> _toList() {
    return <Object?>[
      path,
      parameters,
      linkId,
      attributionId,
      isDeferred,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsDeepLinkData decode(Object result) {
    result as List<Object?>;
    return WtsDeepLinkData(
      path: result[0]! as String,
      parameters: (result[1]! as List<Object?>).cast<WtsParameterData>(),
      linkId: result[2]! as String,
      attributionId: result[3]! as String,
      isDeferred: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsDeepLinkData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) &&
        _deepEquals(parameters, other.parameters) &&
        _deepEquals(linkId, other.linkId) &&
        _deepEquals(attributionId, other.attributionId) &&
        _deepEquals(isDeferred, other.isDeferred);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsRevenueData {
  WtsRevenueData({
    required this.amount,
    required this.currency,
  });

  String amount;

  String currency;

  List<Object?> _toList() {
    return <Object?>[
      amount,
      currency,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsRevenueData decode(Object result) {
    result as List<Object?>;
    return WtsRevenueData(
      amount: result[0]! as String,
      currency: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsRevenueData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(amount, other.amount) &&
        _deepEquals(currency, other.currency);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsConfigurationData {
  WtsConfigurationData({
    required this.appKey,
    this.apiBaseUrl,
  });

  String appKey;

  String? apiBaseUrl;

  List<Object?> _toList() {
    return <Object?>[
      appKey,
      apiBaseUrl,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsConfigurationData decode(Object result) {
    result as List<Object?>;
    return WtsConfigurationData(
      appKey: result[0]! as String,
      apiBaseUrl: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsConfigurationData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(appKey, other.appKey) &&
        _deepEquals(apiBaseUrl, other.apiBaseUrl);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is WtsValueKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is WtsParameterData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is WtsDeepLinkData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is WtsRevenueData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is WtsConfigurationData) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : WtsValueKind.values[value];
      case 130:
        return WtsParameterData.decode(readValue(buffer)!);
      case 131:
        return WtsDeepLinkData.decode(readValue(buffer)!);
      case 132:
        return WtsRevenueData.decode(readValue(buffer)!);
      case 133:
        return WtsConfigurationData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class WtsHostApi {
  /// Constructor for [WtsHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WtsHostApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> configure(WtsConfigurationData configuration) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.configure$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[configuration]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<WtsDeepLinkData> handle(String url) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.handle$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[url]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WtsDeepLinkData;
  }

  Future<WtsDeepLinkData?> getDeferredDeepLink() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.getDeferredDeepLink$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as WtsDeepLinkData?;
  }

  Future<void> track(String eventKey, List<WtsParameterData> properties,
      WtsRevenueData? revenue, String? linkId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.track$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel
        .send(<Object?>[eventKey, properties, revenue, linkId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> flush() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.flush$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
