// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse(
    {Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum WtsValueKind {
  string,
  number,
  boolean,
  date,
  stringArray,
}

class WtsParameterData {
  WtsParameterData({
    required this.key,
    required this.kind,
    this.stringValue,
    this.numberValue,
    this.booleanValue,
    this.stringArrayValue,
  });

  String key;

  WtsValueKind kind;

  String? stringValue;

  double? numberValue;

  bool? booleanValue;

  List<String>? stringArrayValue;

  List<Object?> _toList() {
    return <Object?>[
      key,
      kind,
      stringValue,
      numberValue,
      booleanValue,
      stringArrayValue,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsParameterData decode(Object result) {
    result as List<Object?>;
    return WtsParameterData(
      key: result[0]! as String,
      kind: result[1]! as WtsValueKind,
      stringValue: result[2] as String?,
      numberValue: result[3] as double?,
      booleanValue: result[4] as bool?,
      stringArrayValue: (result[5] as List<Object?>?)?.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsParameterData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(key, other.key) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(stringValue, other.stringValue) &&
        _deepEquals(numberValue, other.numberValue) &&
        _deepEquals(booleanValue, other.booleanValue) &&
        _deepEquals(stringArrayValue, other.stringArrayValue);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsUserUpdateData {
  WtsUserUpdateData({
    required this.set,
    required this.setOnce,
    required this.unset,
    required this.increment,
  });

  List<WtsParameterData> set;

  List<WtsParameterData> setOnce;

  List<String> unset;

  List<WtsIncrementData> increment;

  List<Object?> _toList() {
    return <Object?>[
      set,
      setOnce,
      unset,
      increment,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsUserUpdateData decode(Object result) {
    result as List<Object?>;
    return WtsUserUpdateData(
      set: (result[0]! as List<Object?>).cast<WtsParameterData>(),
      setOnce: (result[1]! as List<Object?>).cast<WtsParameterData>(),
      unset: (result[2]! as List<Object?>).cast<String>(),
      increment: (result[3]! as List<Object?>).cast<WtsIncrementData>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsUserUpdateData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(set, other.set) &&
        _deepEquals(setOnce, other.setOnce) &&
        _deepEquals(unset, other.unset) &&
        _deepEquals(increment, other.increment);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsIncrementData {
  WtsIncrementData({
    required this.key,
    required this.value,
  });

  String key;

  double value;

  List<Object?> _toList() {
    return <Object?>[
      key,
      value,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsIncrementData decode(Object result) {
    result as List<Object?>;
    return WtsIncrementData(
      key: result[0]! as String,
      value: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsIncrementData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(key, other.key) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsReportedAttributionData {
  WtsReportedAttributionData({
    required this.source,
    this.medium,
    this.campaign,
    this.externalRef,
  });

  String source;

  String? medium;

  String? campaign;

  String? externalRef;

  List<Object?> _toList() {
    return <Object?>[
      source,
      medium,
      campaign,
      externalRef,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsReportedAttributionData decode(Object result) {
    result as List<Object?>;
    return WtsReportedAttributionData(
      source: result[0]! as String,
      medium: result[1] as String?,
      campaign: result[2] as String?,
      externalRef: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsReportedAttributionData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(source, other.source) &&
        _deepEquals(medium, other.medium) &&
        _deepEquals(campaign, other.campaign) &&
        _deepEquals(externalRef, other.externalRef);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsDeepLinkData {
  WtsDeepLinkData({
    required this.path,
    required this.parameters,
    required this.linkId,
    required this.attributionId,
    required this.isDeferred,
  });

  String path;

  List<WtsParameterData> parameters;

  String linkId;

  String attributionId;

  bool isDeferred;

  List<Object?> _toList() {
    return <Object?>[
      path,
      parameters,
      linkId,
      attributionId,
      isDeferred,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsDeepLinkData decode(Object result) {
    result as List<Object?>;
    return WtsDeepLinkData(
      path: result[0]! as String,
      parameters: (result[1]! as List<Object?>).cast<WtsParameterData>(),
      linkId: result[2]! as String,
      attributionId: result[3]! as String,
      isDeferred: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsDeepLinkData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) &&
        _deepEquals(parameters, other.parameters) &&
        _deepEquals(linkId, other.linkId) &&
        _deepEquals(attributionId, other.attributionId) &&
        _deepEquals(isDeferred, other.isDeferred);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsRevenueData {
  WtsRevenueData({
    required this.amount,
    required this.currency,
  });

  String amount;

  String currency;

  List<Object?> _toList() {
    return <Object?>[
      amount,
      currency,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsRevenueData decode(Object result) {
    result as List<Object?>;
    return WtsRevenueData(
      amount: result[0]! as String,
      currency: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsRevenueData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(amount, other.amount) &&
        _deepEquals(currency, other.currency);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsConfigurationData {
  WtsConfigurationData({
    required this.appKey,
    this.apiBaseUrl,
    this.collectorBaseUrl,
    required this.experiencesEnabled,
    required this.experienceRenderMode,
    required this.allowedInternalRoutes,
    required this.allowedCallbackKeys,
    required this.allowedDeepLinkHosts,
    required this.allowedDeepLinkSchemes,
    required this.allowedWebOrigins,
    required this.manifestVerificationKeys,
  });

  String appKey;

  String? apiBaseUrl;

  String? collectorBaseUrl;

  bool experiencesEnabled;

  String experienceRenderMode;

  List<String> allowedInternalRoutes;

  List<String> allowedCallbackKeys;

  List<String> allowedDeepLinkHosts;

  List<String> allowedDeepLinkSchemes;

  List<String> allowedWebOrigins;

  List<WtsManifestVerificationKeyData> manifestVerificationKeys;

  List<Object?> _toList() {
    return <Object?>[
      appKey,
      apiBaseUrl,
      collectorBaseUrl,
      experiencesEnabled,
      experienceRenderMode,
      allowedInternalRoutes,
      allowedCallbackKeys,
      allowedDeepLinkHosts,
      allowedDeepLinkSchemes,
      allowedWebOrigins,
      manifestVerificationKeys,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsConfigurationData decode(Object result) {
    result as List<Object?>;
    return WtsConfigurationData(
      appKey: result[0]! as String,
      apiBaseUrl: result[1] as String?,
      collectorBaseUrl: result[2] as String?,
      experiencesEnabled: result[3]! as bool,
      experienceRenderMode: result[4]! as String,
      allowedInternalRoutes: (result[5]! as List<Object?>).cast<String>(),
      allowedCallbackKeys: (result[6]! as List<Object?>).cast<String>(),
      allowedDeepLinkHosts: (result[7]! as List<Object?>).cast<String>(),
      allowedDeepLinkSchemes: (result[8]! as List<Object?>).cast<String>(),
      allowedWebOrigins: (result[9]! as List<Object?>).cast<String>(),
      manifestVerificationKeys:
          (result[10]! as List<Object?>).cast<WtsManifestVerificationKeyData>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsConfigurationData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(appKey, other.appKey) &&
        _deepEquals(apiBaseUrl, other.apiBaseUrl) &&
        _deepEquals(collectorBaseUrl, other.collectorBaseUrl) &&
        _deepEquals(experiencesEnabled, other.experiencesEnabled) &&
        _deepEquals(experienceRenderMode, other.experienceRenderMode) &&
        _deepEquals(allowedInternalRoutes, other.allowedInternalRoutes) &&
        _deepEquals(allowedCallbackKeys, other.allowedCallbackKeys) &&
        _deepEquals(allowedDeepLinkHosts, other.allowedDeepLinkHosts) &&
        _deepEquals(allowedDeepLinkSchemes, other.allowedDeepLinkSchemes) &&
        _deepEquals(allowedWebOrigins, other.allowedWebOrigins) &&
        _deepEquals(manifestVerificationKeys, other.manifestVerificationKeys);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsManifestVerificationKeyData {
  WtsManifestVerificationKeyData({
    required this.kid,
    required this.value,
  });

  String kid;

  String value;

  List<Object?> _toList() {
    return <Object?>[
      kid,
      value,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsManifestVerificationKeyData decode(Object result) {
    result as List<Object?>;
    return WtsManifestVerificationKeyData(
      kid: result[0]! as String,
      value: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsManifestVerificationKeyData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kid, other.kid) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsExperienceDiagnosticsData {
  WtsExperienceDiagnosticsData({
    required this.enabled,
    required this.consent,
    required this.queued,
    required this.presenting,
    required this.testDeviceToken,
    this.lastErrorCode,
  });

  bool enabled;

  String consent;

  int queued;

  bool presenting;

  String testDeviceToken;

  String? lastErrorCode;

  List<Object?> _toList() {
    return <Object?>[
      enabled,
      consent,
      queued,
      presenting,
      testDeviceToken,
      lastErrorCode,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsExperienceDiagnosticsData decode(Object result) {
    result as List<Object?>;
    return WtsExperienceDiagnosticsData(
      enabled: result[0]! as bool,
      consent: result[1]! as String,
      queued: result[2]! as int,
      presenting: result[3]! as bool,
      testDeviceToken: result[4]! as String,
      lastErrorCode: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsExperienceDiagnosticsData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(enabled, other.enabled) &&
        _deepEquals(consent, other.consent) &&
        _deepEquals(queued, other.queued) &&
        _deepEquals(presenting, other.presenting) &&
        _deepEquals(testDeviceToken, other.testDeviceToken) &&
        _deepEquals(lastErrorCode, other.lastErrorCode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsExperienceActionData {
  WtsExperienceActionData({
    required this.id,
    required this.label,
    required this.type,
    this.target,
  });

  String id;

  String label;

  String type;

  String? target;

  List<Object?> _toList() {
    return <Object?>[
      id,
      label,
      type,
      target,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsExperienceActionData decode(Object result) {
    result as List<Object?>;
    return WtsExperienceActionData(
      id: result[0]! as String,
      label: result[1]! as String,
      type: result[2]! as String,
      target: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsExperienceActionData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(label, other.label) &&
        _deepEquals(type, other.type) &&
        _deepEquals(target, other.target);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsExperienceTranslationData {
  WtsExperienceTranslationData({
    required this.locale,
    required this.title,
    required this.description,
    this.primaryAction,
    this.secondaryAction,
  });

  String locale;

  String title;

  String description;

  WtsExperienceActionData? primaryAction;

  WtsExperienceActionData? secondaryAction;

  List<Object?> _toList() {
    return <Object?>[
      locale,
      title,
      description,
      primaryAction,
      secondaryAction,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsExperienceTranslationData decode(Object result) {
    result as List<Object?>;
    return WtsExperienceTranslationData(
      locale: result[0]! as String,
      title: result[1]! as String,
      description: result[2]! as String,
      primaryAction: result[3] as WtsExperienceActionData?,
      secondaryAction: result[4] as WtsExperienceActionData?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsExperienceTranslationData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(locale, other.locale) &&
        _deepEquals(title, other.title) &&
        _deepEquals(description, other.description) &&
        _deepEquals(primaryAction, other.primaryAction) &&
        _deepEquals(secondaryAction, other.secondaryAction);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsExperienceData {
  WtsExperienceData({
    required this.campaignId,
    required this.campaignVersionId,
    required this.assignmentId,
    required this.variantId,
    required this.placement,
    required this.priority,
    required this.translations,
    required this.closeable,
    required this.themePreset,
    required this.delaySeconds,
    this.autoCloseSeconds,
    this.assetUrl,
  });

  String campaignId;

  String campaignVersionId;

  String assignmentId;

  String variantId;

  String placement;

  int priority;

  List<WtsExperienceTranslationData> translations;

  bool closeable;

  String themePreset;

  double delaySeconds;

  double? autoCloseSeconds;

  String? assetUrl;

  List<Object?> _toList() {
    return <Object?>[
      campaignId,
      campaignVersionId,
      assignmentId,
      variantId,
      placement,
      priority,
      translations,
      closeable,
      themePreset,
      delaySeconds,
      autoCloseSeconds,
      assetUrl,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsExperienceData decode(Object result) {
    result as List<Object?>;
    return WtsExperienceData(
      campaignId: result[0]! as String,
      campaignVersionId: result[1]! as String,
      assignmentId: result[2]! as String,
      variantId: result[3]! as String,
      placement: result[4]! as String,
      priority: result[5]! as int,
      translations:
          (result[6]! as List<Object?>).cast<WtsExperienceTranslationData>(),
      closeable: result[7]! as bool,
      themePreset: result[8]! as String,
      delaySeconds: result[9]! as double,
      autoCloseSeconds: result[10] as double?,
      assetUrl: result[11] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsExperienceData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(campaignId, other.campaignId) &&
        _deepEquals(campaignVersionId, other.campaignVersionId) &&
        _deepEquals(assignmentId, other.assignmentId) &&
        _deepEquals(variantId, other.variantId) &&
        _deepEquals(placement, other.placement) &&
        _deepEquals(priority, other.priority) &&
        _deepEquals(translations, other.translations) &&
        _deepEquals(closeable, other.closeable) &&
        _deepEquals(themePreset, other.themePreset) &&
        _deepEquals(delaySeconds, other.delaySeconds) &&
        _deepEquals(autoCloseSeconds, other.autoCloseSeconds) &&
        _deepEquals(assetUrl, other.assetUrl);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsExperiencePresentationHandleData {
  WtsExperiencePresentationHandleData({
    required this.exposureId,
  });

  String exposureId;

  List<Object?> _toList() {
    return <Object?>[
      exposureId,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsExperiencePresentationHandleData decode(Object result) {
    result as List<Object?>;
    return WtsExperiencePresentationHandleData(
      exposureId: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsExperiencePresentationHandleData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(exposureId, other.exposureId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsExperienceManualPresentationData {
  WtsExperienceManualPresentationData({
    required this.experience,
    required this.handle,
  });

  WtsExperienceData experience;

  WtsExperiencePresentationHandleData handle;

  List<Object?> _toList() {
    return <Object?>[
      experience,
      handle,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsExperienceManualPresentationData decode(Object result) {
    result as List<Object?>;
    return WtsExperienceManualPresentationData(
      experience: result[0]! as WtsExperienceData,
      handle: result[1]! as WtsExperiencePresentationHandleData,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsExperienceManualPresentationData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(experience, other.experience) &&
        _deepEquals(handle, other.handle);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsExperienceLifecycleOutcomeData {
  WtsExperienceLifecycleOutcomeData({
    required this.accepted,
    required this.idempotent,
    this.code,
  });

  bool accepted;

  bool idempotent;

  String? code;

  List<Object?> _toList() {
    return <Object?>[
      accepted,
      idempotent,
      code,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsExperienceLifecycleOutcomeData decode(Object result) {
    result as List<Object?>;
    return WtsExperienceLifecycleOutcomeData(
      accepted: result[0]! as bool,
      idempotent: result[1]! as bool,
      code: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsExperienceLifecycleOutcomeData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accepted, other.accepted) &&
        _deepEquals(idempotent, other.idempotent) &&
        _deepEquals(code, other.code);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsTestSessionCheckData {
  WtsTestSessionCheckData({
    required this.key,
    required this.status,
    this.code,
    this.message,
  });

  String key;

  String status;

  String? code;

  String? message;

  List<Object?> _toList() {
    return <Object?>[
      key,
      status,
      code,
      message,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsTestSessionCheckData decode(Object result) {
    result as List<Object?>;
    return WtsTestSessionCheckData(
      key: result[0]! as String,
      status: result[1]! as String,
      code: result[2] as String?,
      message: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsTestSessionCheckData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(key, other.key) &&
        _deepEquals(status, other.status) &&
        _deepEquals(code, other.code) &&
        _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsTestSessionJoinData {
  WtsTestSessionJoinData({
    required this.accepted,
    required this.joined,
    required this.compatible,
    required this.checks,
    this.requiredSdkVersion,
    this.sessionId,
    this.expiresAt,
    this.testProfileExternalUserId,
    this.errorCode,
  });

  bool accepted;

  bool joined;

  bool compatible;

  List<WtsTestSessionCheckData> checks;

  String? requiredSdkVersion;

  String? sessionId;

  String? expiresAt;

  String? testProfileExternalUserId;

  String? errorCode;

  List<Object?> _toList() {
    return <Object?>[
      accepted,
      joined,
      compatible,
      checks,
      requiredSdkVersion,
      sessionId,
      expiresAt,
      testProfileExternalUserId,
      errorCode,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsTestSessionJoinData decode(Object result) {
    result as List<Object?>;
    return WtsTestSessionJoinData(
      accepted: result[0]! as bool,
      joined: result[1]! as bool,
      compatible: result[2]! as bool,
      checks: (result[3]! as List<Object?>).cast<WtsTestSessionCheckData>(),
      requiredSdkVersion: result[4] as String?,
      sessionId: result[5] as String?,
      expiresAt: result[6] as String?,
      testProfileExternalUserId: result[7] as String?,
      errorCode: result[8] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsTestSessionJoinData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accepted, other.accepted) &&
        _deepEquals(joined, other.joined) &&
        _deepEquals(compatible, other.compatible) &&
        _deepEquals(checks, other.checks) &&
        _deepEquals(requiredSdkVersion, other.requiredSdkVersion) &&
        _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(expiresAt, other.expiresAt) &&
        _deepEquals(
            testProfileExternalUserId, other.testProfileExternalUserId) &&
        _deepEquals(errorCode, other.errorCode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsTestSessionDiagnosticsData {
  WtsTestSessionDiagnosticsData({
    required this.joined,
    required this.compatible,
    required this.checks,
    required this.pendingSignals,
    this.sessionId,
    this.expiresAt,
    this.requiredSdkVersion,
    this.lastErrorCode,
  });

  bool joined;

  bool compatible;

  List<WtsTestSessionCheckData> checks;

  int pendingSignals;

  String? sessionId;

  String? expiresAt;

  String? requiredSdkVersion;

  String? lastErrorCode;

  List<Object?> _toList() {
    return <Object?>[
      joined,
      compatible,
      checks,
      pendingSignals,
      sessionId,
      expiresAt,
      requiredSdkVersion,
      lastErrorCode,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsTestSessionDiagnosticsData decode(Object result) {
    result as List<Object?>;
    return WtsTestSessionDiagnosticsData(
      joined: result[0]! as bool,
      compatible: result[1]! as bool,
      checks: (result[2]! as List<Object?>).cast<WtsTestSessionCheckData>(),
      pendingSignals: result[3]! as int,
      sessionId: result[4] as String?,
      expiresAt: result[5] as String?,
      requiredSdkVersion: result[6] as String?,
      lastErrorCode: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsTestSessionDiagnosticsData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(joined, other.joined) &&
        _deepEquals(compatible, other.compatible) &&
        _deepEquals(checks, other.checks) &&
        _deepEquals(pendingSignals, other.pendingSignals) &&
        _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(expiresAt, other.expiresAt) &&
        _deepEquals(requiredSdkVersion, other.requiredSdkVersion) &&
        _deepEquals(lastErrorCode, other.lastErrorCode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsTestSessionProbeLinkData {
  WtsTestSessionProbeLinkData({
    required this.id,
    required this.path,
    required this.parametersJson,
  });

  String id;

  String path;

  String parametersJson;

  List<Object?> _toList() {
    return <Object?>[
      id,
      path,
      parametersJson,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsTestSessionProbeLinkData decode(Object result) {
    result as List<Object?>;
    return WtsTestSessionProbeLinkData(
      id: result[0]! as String,
      path: result[1]! as String,
      parametersJson: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsTestSessionProbeLinkData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(path, other.path) &&
        _deepEquals(parametersJson, other.parametersJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsTestSessionProbeData {
  WtsTestSessionProbeData({
    required this.match,
    required this.status,
    required this.code,
    required this.originalUrl,
    required this.fallbackUrl,
    this.link,
  });

  bool match;

  String status;

  String code;

  String originalUrl;

  String fallbackUrl;

  WtsTestSessionProbeLinkData? link;

  List<Object?> _toList() {
    return <Object?>[
      match,
      status,
      code,
      originalUrl,
      fallbackUrl,
      link,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsTestSessionProbeData decode(Object result) {
    result as List<Object?>;
    return WtsTestSessionProbeData(
      match: result[0]! as bool,
      status: result[1]! as String,
      code: result[2]! as String,
      originalUrl: result[3]! as String,
      fallbackUrl: result[4]! as String,
      link: result[5] as WtsTestSessionProbeLinkData?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsTestSessionProbeData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(match, other.match) &&
        _deepEquals(status, other.status) &&
        _deepEquals(code, other.code) &&
        _deepEquals(originalUrl, other.originalUrl) &&
        _deepEquals(fallbackUrl, other.fallbackUrl) &&
        _deepEquals(link, other.link);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WtsTestSessionProbeRunData {
  WtsTestSessionProbeRunData({
    required this.accepted,
    required this.emitted,
    required this.skipped,
    required this.pendingSignals,
    this.experienceDecisionJson,
  });

  bool accepted;

  List<String> emitted;

  List<String> skipped;

  int pendingSignals;

  String? experienceDecisionJson;

  List<Object?> _toList() {
    return <Object?>[
      accepted,
      emitted,
      skipped,
      pendingSignals,
      experienceDecisionJson,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WtsTestSessionProbeRunData decode(Object result) {
    result as List<Object?>;
    return WtsTestSessionProbeRunData(
      accepted: result[0]! as bool,
      emitted: (result[1]! as List<Object?>).cast<String>(),
      skipped: (result[2]! as List<Object?>).cast<String>(),
      pendingSignals: result[3]! as int,
      experienceDecisionJson: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WtsTestSessionProbeRunData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accepted, other.accepted) &&
        _deepEquals(emitted, other.emitted) &&
        _deepEquals(skipped, other.skipped) &&
        _deepEquals(pendingSignals, other.pendingSignals) &&
        _deepEquals(experienceDecisionJson, other.experienceDecisionJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is WtsValueKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is WtsParameterData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is WtsUserUpdateData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is WtsIncrementData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is WtsReportedAttributionData) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is WtsDeepLinkData) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is WtsRevenueData) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is WtsConfigurationData) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is WtsManifestVerificationKeyData) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is WtsExperienceDiagnosticsData) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is WtsExperienceActionData) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is WtsExperienceTranslationData) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is WtsExperienceData) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is WtsExperiencePresentationHandleData) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is WtsExperienceManualPresentationData) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is WtsExperienceLifecycleOutcomeData) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is WtsTestSessionCheckData) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is WtsTestSessionJoinData) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is WtsTestSessionDiagnosticsData) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is WtsTestSessionProbeLinkData) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is WtsTestSessionProbeData) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is WtsTestSessionProbeRunData) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : WtsValueKind.values[value];
      case 130:
        return WtsParameterData.decode(readValue(buffer)!);
      case 131:
        return WtsUserUpdateData.decode(readValue(buffer)!);
      case 132:
        return WtsIncrementData.decode(readValue(buffer)!);
      case 133:
        return WtsReportedAttributionData.decode(readValue(buffer)!);
      case 134:
        return WtsDeepLinkData.decode(readValue(buffer)!);
      case 135:
        return WtsRevenueData.decode(readValue(buffer)!);
      case 136:
        return WtsConfigurationData.decode(readValue(buffer)!);
      case 137:
        return WtsManifestVerificationKeyData.decode(readValue(buffer)!);
      case 138:
        return WtsExperienceDiagnosticsData.decode(readValue(buffer)!);
      case 139:
        return WtsExperienceActionData.decode(readValue(buffer)!);
      case 140:
        return WtsExperienceTranslationData.decode(readValue(buffer)!);
      case 141:
        return WtsExperienceData.decode(readValue(buffer)!);
      case 142:
        return WtsExperiencePresentationHandleData.decode(readValue(buffer)!);
      case 143:
        return WtsExperienceManualPresentationData.decode(readValue(buffer)!);
      case 144:
        return WtsExperienceLifecycleOutcomeData.decode(readValue(buffer)!);
      case 145:
        return WtsTestSessionCheckData.decode(readValue(buffer)!);
      case 146:
        return WtsTestSessionJoinData.decode(readValue(buffer)!);
      case 147:
        return WtsTestSessionDiagnosticsData.decode(readValue(buffer)!);
      case 148:
        return WtsTestSessionProbeLinkData.decode(readValue(buffer)!);
      case 149:
        return WtsTestSessionProbeData.decode(readValue(buffer)!);
      case 150:
        return WtsTestSessionProbeRunData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class WtsFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onExperienceAvailable(WtsExperienceManualPresentationData presentation);

  void onExperienceAction(
      WtsExperienceData experience, WtsExperienceActionData action);

  static void setUp(
    WtsFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix =
        messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.wts_sdk.WtsFlutterApi.onExperienceAvailable$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final WtsExperienceManualPresentationData arg_presentation =
              args[0]! as WtsExperienceManualPresentationData;
          try {
            api.onExperienceAvailable(arg_presentation);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.wts_sdk.WtsFlutterApi.onExperienceAction$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final WtsExperienceData arg_experience =
              args[0]! as WtsExperienceData;
          final WtsExperienceActionData arg_action =
              args[1]! as WtsExperienceActionData;
          try {
            api.onExperienceAction(arg_experience, arg_action);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

class WtsHostApi {
  /// Constructor for [WtsHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WtsHostApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> configure(WtsConfigurationData configuration) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.configure$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[configuration]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<WtsDeepLinkData> handle(String url) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.handle$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[url]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WtsDeepLinkData;
  }

  Future<WtsDeepLinkData?> getDeferredDeepLink() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.getDeferredDeepLink$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as WtsDeepLinkData?;
  }

  Future<void> setProfileConsent(bool granted) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.setProfileConsent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[granted]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> identify(
      String externalUserId, List<WtsParameterData> attributes) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.identify$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[externalUserId, attributes]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> updateUser(WtsUserUpdateData update) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.updateUser$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[update]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setReportedAttribution(
      WtsReportedAttributionData attribution) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.setReportedAttribution$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[attribution]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> resetIdentity() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.resetIdentity$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> track(String eventKey, List<WtsParameterData> properties,
      WtsRevenueData? revenue, String? linkId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.track$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel
        .send(<Object?>[eventKey, properties, revenue, linkId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> screen(String name, List<WtsParameterData> properties) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.screen$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[name, properties]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String> setExperienceConsent(String consent) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.setExperienceConsent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[consent]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<bool> presentNextExperience() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.presentNextExperience$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> dismissCurrentExperience() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.dismissCurrentExperience$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<WtsExperienceDiagnosticsData> getExperienceDiagnostics() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.getExperienceDiagnostics$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WtsExperienceDiagnosticsData;
  }

  Future<WtsExperienceLifecycleOutcomeData> acknowledgeExperienceRender(
      WtsExperiencePresentationHandleData handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.acknowledgeExperienceRender$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[handle]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WtsExperienceLifecycleOutcomeData;
  }

  Future<WtsExperienceLifecycleOutcomeData> acknowledgeExperienceImpression(
      WtsExperiencePresentationHandleData handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.acknowledgeExperienceImpression$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[handle]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WtsExperienceLifecycleOutcomeData;
  }

  Future<WtsExperienceLifecycleOutcomeData> reportExperienceAction(
      WtsExperiencePresentationHandleData handle, String actionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.reportExperienceAction$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[handle, actionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WtsExperienceLifecycleOutcomeData;
  }

  Future<WtsExperienceLifecycleOutcomeData> dismissExperience(
      WtsExperiencePresentationHandleData handle,
      String reason,
      String? failureCode) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.dismissExperience$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[handle, reason, failureCode]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WtsExperienceLifecycleOutcomeData;
  }

  Future<WtsTestSessionJoinData> joinTestSession(String pairing) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.joinTestSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[pairing]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WtsTestSessionJoinData;
  }

  Future<bool> leaveTestSession() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.leaveTestSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<WtsTestSessionDiagnosticsData> getTestSessionDiagnostics() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.getTestSessionDiagnostics$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WtsTestSessionDiagnosticsData;
  }

  Future<WtsTestSessionProbeData> probeTestSessionUrl(String url) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.probeTestSessionUrl$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[url]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WtsTestSessionProbeData;
  }

  Future<WtsTestSessionProbeRunData> runTestSessionProbes() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.runTestSessionProbes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WtsTestSessionProbeRunData;
  }

  Future<bool> reportTestSessionExperienceInteraction(
      String interaction) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.reportTestSessionExperienceInteraction$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[interaction]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> flush() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.wts_sdk.WtsHostApi.flush$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
