// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package co.wetus.sdk.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object WtsMessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class WtsValueKind(val raw: Int) {
  STRING(0),
  NUMBER(1),
  BOOLEAN(2),
  DATE(3),
  STRING_ARRAY(4);

  companion object {
    fun ofRaw(raw: Int): WtsValueKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsParameterData (
  val key: String,
  val kind: WtsValueKind,
  val stringValue: String? = null,
  val numberValue: Double? = null,
  val booleanValue: Boolean? = null,
  val stringArrayValue: List<String>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsParameterData {
      val key = pigeonVar_list[0] as String
      val kind = pigeonVar_list[1] as WtsValueKind
      val stringValue = pigeonVar_list[2] as String?
      val numberValue = pigeonVar_list[3] as Double?
      val booleanValue = pigeonVar_list[4] as Boolean?
      val stringArrayValue = pigeonVar_list[5] as List<String>?
      return WtsParameterData(key, kind, stringValue, numberValue, booleanValue, stringArrayValue)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      key,
      kind,
      stringValue,
      numberValue,
      booleanValue,
      stringArrayValue,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsParameterData
    return WtsMessagesPigeonUtils.deepEquals(this.key, other.key) && WtsMessagesPigeonUtils.deepEquals(this.kind, other.kind) && WtsMessagesPigeonUtils.deepEquals(this.stringValue, other.stringValue) && WtsMessagesPigeonUtils.deepEquals(this.numberValue, other.numberValue) && WtsMessagesPigeonUtils.deepEquals(this.booleanValue, other.booleanValue) && WtsMessagesPigeonUtils.deepEquals(this.stringArrayValue, other.stringArrayValue)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.key)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.kind)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.stringValue)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.numberValue)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.booleanValue)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.stringArrayValue)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsUserUpdateData (
  val set: List<WtsParameterData>,
  val setOnce: List<WtsParameterData>,
  val unset: List<String>,
  val increment: List<WtsIncrementData>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsUserUpdateData {
      val set = pigeonVar_list[0] as List<WtsParameterData>
      val setOnce = pigeonVar_list[1] as List<WtsParameterData>
      val unset = pigeonVar_list[2] as List<String>
      val increment = pigeonVar_list[3] as List<WtsIncrementData>
      return WtsUserUpdateData(set, setOnce, unset, increment)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      set,
      setOnce,
      unset,
      increment,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsUserUpdateData
    return WtsMessagesPigeonUtils.deepEquals(this.set, other.set) && WtsMessagesPigeonUtils.deepEquals(this.setOnce, other.setOnce) && WtsMessagesPigeonUtils.deepEquals(this.unset, other.unset) && WtsMessagesPigeonUtils.deepEquals(this.increment, other.increment)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.set)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.setOnce)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.unset)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.increment)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsIncrementData (
  val key: String,
  val value: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsIncrementData {
      val key = pigeonVar_list[0] as String
      val value = pigeonVar_list[1] as Double
      return WtsIncrementData(key, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      key,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsIncrementData
    return WtsMessagesPigeonUtils.deepEquals(this.key, other.key) && WtsMessagesPigeonUtils.deepEquals(this.value, other.value)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.key)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.value)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsReportedAttributionData (
  val source: String,
  val medium: String? = null,
  val campaign: String? = null,
  val externalRef: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsReportedAttributionData {
      val source = pigeonVar_list[0] as String
      val medium = pigeonVar_list[1] as String?
      val campaign = pigeonVar_list[2] as String?
      val externalRef = pigeonVar_list[3] as String?
      return WtsReportedAttributionData(source, medium, campaign, externalRef)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      source,
      medium,
      campaign,
      externalRef,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsReportedAttributionData
    return WtsMessagesPigeonUtils.deepEquals(this.source, other.source) && WtsMessagesPigeonUtils.deepEquals(this.medium, other.medium) && WtsMessagesPigeonUtils.deepEquals(this.campaign, other.campaign) && WtsMessagesPigeonUtils.deepEquals(this.externalRef, other.externalRef)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.source)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.medium)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.campaign)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.externalRef)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsDeepLinkData (
  val path: String,
  val parameters: List<WtsParameterData>,
  val linkId: String,
  val attributionId: String,
  val isDeferred: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsDeepLinkData {
      val path = pigeonVar_list[0] as String
      val parameters = pigeonVar_list[1] as List<WtsParameterData>
      val linkId = pigeonVar_list[2] as String
      val attributionId = pigeonVar_list[3] as String
      val isDeferred = pigeonVar_list[4] as Boolean
      return WtsDeepLinkData(path, parameters, linkId, attributionId, isDeferred)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      parameters,
      linkId,
      attributionId,
      isDeferred,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsDeepLinkData
    return WtsMessagesPigeonUtils.deepEquals(this.path, other.path) && WtsMessagesPigeonUtils.deepEquals(this.parameters, other.parameters) && WtsMessagesPigeonUtils.deepEquals(this.linkId, other.linkId) && WtsMessagesPigeonUtils.deepEquals(this.attributionId, other.attributionId) && WtsMessagesPigeonUtils.deepEquals(this.isDeferred, other.isDeferred)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.path)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.parameters)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.linkId)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.attributionId)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.isDeferred)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsRevenueData (
  val amount: String,
  val currency: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsRevenueData {
      val amount = pigeonVar_list[0] as String
      val currency = pigeonVar_list[1] as String
      return WtsRevenueData(amount, currency)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      amount,
      currency,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsRevenueData
    return WtsMessagesPigeonUtils.deepEquals(this.amount, other.amount) && WtsMessagesPigeonUtils.deepEquals(this.currency, other.currency)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.amount)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.currency)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsConfigurationData (
  val appKey: String,
  val apiBaseUrl: String? = null,
  val collectorBaseUrl: String? = null,
  val experiencesEnabled: Boolean,
  val experienceRenderMode: String,
  val allowedInternalRoutes: List<String>,
  val allowedCallbackKeys: List<String>,
  val allowedDeepLinkHosts: List<String>,
  val allowedDeepLinkSchemes: List<String>,
  val allowedWebOrigins: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsConfigurationData {
      val appKey = pigeonVar_list[0] as String
      val apiBaseUrl = pigeonVar_list[1] as String?
      val collectorBaseUrl = pigeonVar_list[2] as String?
      val experiencesEnabled = pigeonVar_list[3] as Boolean
      val experienceRenderMode = pigeonVar_list[4] as String
      val allowedInternalRoutes = pigeonVar_list[5] as List<String>
      val allowedCallbackKeys = pigeonVar_list[6] as List<String>
      val allowedDeepLinkHosts = pigeonVar_list[7] as List<String>
      val allowedDeepLinkSchemes = pigeonVar_list[8] as List<String>
      val allowedWebOrigins = pigeonVar_list[9] as List<String>
      return WtsConfigurationData(appKey, apiBaseUrl, collectorBaseUrl, experiencesEnabled, experienceRenderMode, allowedInternalRoutes, allowedCallbackKeys, allowedDeepLinkHosts, allowedDeepLinkSchemes, allowedWebOrigins)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      appKey,
      apiBaseUrl,
      collectorBaseUrl,
      experiencesEnabled,
      experienceRenderMode,
      allowedInternalRoutes,
      allowedCallbackKeys,
      allowedDeepLinkHosts,
      allowedDeepLinkSchemes,
      allowedWebOrigins,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsConfigurationData
    return WtsMessagesPigeonUtils.deepEquals(this.appKey, other.appKey) && WtsMessagesPigeonUtils.deepEquals(this.apiBaseUrl, other.apiBaseUrl) && WtsMessagesPigeonUtils.deepEquals(this.collectorBaseUrl, other.collectorBaseUrl) && WtsMessagesPigeonUtils.deepEquals(this.experiencesEnabled, other.experiencesEnabled) && WtsMessagesPigeonUtils.deepEquals(this.experienceRenderMode, other.experienceRenderMode) && WtsMessagesPigeonUtils.deepEquals(this.allowedInternalRoutes, other.allowedInternalRoutes) && WtsMessagesPigeonUtils.deepEquals(this.allowedCallbackKeys, other.allowedCallbackKeys) && WtsMessagesPigeonUtils.deepEquals(this.allowedDeepLinkHosts, other.allowedDeepLinkHosts) && WtsMessagesPigeonUtils.deepEquals(this.allowedDeepLinkSchemes, other.allowedDeepLinkSchemes) && WtsMessagesPigeonUtils.deepEquals(this.allowedWebOrigins, other.allowedWebOrigins)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.appKey)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.apiBaseUrl)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.collectorBaseUrl)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.experiencesEnabled)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.experienceRenderMode)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.allowedInternalRoutes)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.allowedCallbackKeys)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.allowedDeepLinkHosts)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.allowedDeepLinkSchemes)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.allowedWebOrigins)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsExperienceDiagnosticsData (
  val enabled: Boolean,
  val consent: String,
  val queued: Long,
  val presenting: Boolean,
  val testDeviceToken: String,
  val lastErrorCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsExperienceDiagnosticsData {
      val enabled = pigeonVar_list[0] as Boolean
      val consent = pigeonVar_list[1] as String
      val queued = pigeonVar_list[2] as Long
      val presenting = pigeonVar_list[3] as Boolean
      val testDeviceToken = pigeonVar_list[4] as String
      val lastErrorCode = pigeonVar_list[5] as String?
      return WtsExperienceDiagnosticsData(enabled, consent, queued, presenting, testDeviceToken, lastErrorCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      enabled,
      consent,
      queued,
      presenting,
      testDeviceToken,
      lastErrorCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsExperienceDiagnosticsData
    return WtsMessagesPigeonUtils.deepEquals(this.enabled, other.enabled) && WtsMessagesPigeonUtils.deepEquals(this.consent, other.consent) && WtsMessagesPigeonUtils.deepEquals(this.queued, other.queued) && WtsMessagesPigeonUtils.deepEquals(this.presenting, other.presenting) && WtsMessagesPigeonUtils.deepEquals(this.testDeviceToken, other.testDeviceToken) && WtsMessagesPigeonUtils.deepEquals(this.lastErrorCode, other.lastErrorCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.enabled)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.consent)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.queued)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.presenting)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.testDeviceToken)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.lastErrorCode)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsExperienceActionData (
  val id: String,
  val label: String,
  val type: String,
  val target: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsExperienceActionData {
      val id = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      val type = pigeonVar_list[2] as String
      val target = pigeonVar_list[3] as String?
      return WtsExperienceActionData(id, label, type, target)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      label,
      type,
      target,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsExperienceActionData
    return WtsMessagesPigeonUtils.deepEquals(this.id, other.id) && WtsMessagesPigeonUtils.deepEquals(this.label, other.label) && WtsMessagesPigeonUtils.deepEquals(this.type, other.type) && WtsMessagesPigeonUtils.deepEquals(this.target, other.target)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.label)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.target)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsExperienceTranslationData (
  val locale: String,
  val title: String,
  val description: String,
  val primaryAction: WtsExperienceActionData? = null,
  val secondaryAction: WtsExperienceActionData? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsExperienceTranslationData {
      val locale = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val description = pigeonVar_list[2] as String
      val primaryAction = pigeonVar_list[3] as WtsExperienceActionData?
      val secondaryAction = pigeonVar_list[4] as WtsExperienceActionData?
      return WtsExperienceTranslationData(locale, title, description, primaryAction, secondaryAction)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      locale,
      title,
      description,
      primaryAction,
      secondaryAction,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsExperienceTranslationData
    return WtsMessagesPigeonUtils.deepEquals(this.locale, other.locale) && WtsMessagesPigeonUtils.deepEquals(this.title, other.title) && WtsMessagesPigeonUtils.deepEquals(this.description, other.description) && WtsMessagesPigeonUtils.deepEquals(this.primaryAction, other.primaryAction) && WtsMessagesPigeonUtils.deepEquals(this.secondaryAction, other.secondaryAction)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.locale)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.title)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.description)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.primaryAction)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.secondaryAction)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsExperienceData (
  val campaignId: String,
  val campaignVersionId: String,
  val assignmentId: String,
  val variantId: String,
  val exposureId: String,
  val placement: String,
  val priority: Long,
  val translations: List<WtsExperienceTranslationData>,
  val closeable: Boolean,
  val themePreset: String,
  val delaySeconds: Double,
  val autoCloseSeconds: Double? = null,
  val assetUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsExperienceData {
      val campaignId = pigeonVar_list[0] as String
      val campaignVersionId = pigeonVar_list[1] as String
      val assignmentId = pigeonVar_list[2] as String
      val variantId = pigeonVar_list[3] as String
      val exposureId = pigeonVar_list[4] as String
      val placement = pigeonVar_list[5] as String
      val priority = pigeonVar_list[6] as Long
      val translations = pigeonVar_list[7] as List<WtsExperienceTranslationData>
      val closeable = pigeonVar_list[8] as Boolean
      val themePreset = pigeonVar_list[9] as String
      val delaySeconds = pigeonVar_list[10] as Double
      val autoCloseSeconds = pigeonVar_list[11] as Double?
      val assetUrl = pigeonVar_list[12] as String?
      return WtsExperienceData(campaignId, campaignVersionId, assignmentId, variantId, exposureId, placement, priority, translations, closeable, themePreset, delaySeconds, autoCloseSeconds, assetUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      campaignId,
      campaignVersionId,
      assignmentId,
      variantId,
      exposureId,
      placement,
      priority,
      translations,
      closeable,
      themePreset,
      delaySeconds,
      autoCloseSeconds,
      assetUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsExperienceData
    return WtsMessagesPigeonUtils.deepEquals(this.campaignId, other.campaignId) && WtsMessagesPigeonUtils.deepEquals(this.campaignVersionId, other.campaignVersionId) && WtsMessagesPigeonUtils.deepEquals(this.assignmentId, other.assignmentId) && WtsMessagesPigeonUtils.deepEquals(this.variantId, other.variantId) && WtsMessagesPigeonUtils.deepEquals(this.exposureId, other.exposureId) && WtsMessagesPigeonUtils.deepEquals(this.placement, other.placement) && WtsMessagesPigeonUtils.deepEquals(this.priority, other.priority) && WtsMessagesPigeonUtils.deepEquals(this.translations, other.translations) && WtsMessagesPigeonUtils.deepEquals(this.closeable, other.closeable) && WtsMessagesPigeonUtils.deepEquals(this.themePreset, other.themePreset) && WtsMessagesPigeonUtils.deepEquals(this.delaySeconds, other.delaySeconds) && WtsMessagesPigeonUtils.deepEquals(this.autoCloseSeconds, other.autoCloseSeconds) && WtsMessagesPigeonUtils.deepEquals(this.assetUrl, other.assetUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.campaignId)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.campaignVersionId)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.assignmentId)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.variantId)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.exposureId)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.placement)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.priority)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.translations)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.closeable)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.themePreset)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.delaySeconds)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.autoCloseSeconds)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.assetUrl)
    return result
  }
}
private open class WtsMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WtsValueKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsParameterData.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsUserUpdateData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsIncrementData.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsReportedAttributionData.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsDeepLinkData.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsRevenueData.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsConfigurationData.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsExperienceDiagnosticsData.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsExperienceActionData.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsExperienceTranslationData.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsExperienceData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is WtsValueKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is WtsParameterData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is WtsUserUpdateData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is WtsIncrementData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is WtsReportedAttributionData -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is WtsDeepLinkData -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is WtsRevenueData -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is WtsConfigurationData -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is WtsExperienceDiagnosticsData -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is WtsExperienceActionData -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is WtsExperienceTranslationData -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is WtsExperienceData -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class WtsFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by WtsFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      WtsMessagesPigeonCodec()
    }
  }
  fun onExperienceAvailable(experienceArg: WtsExperienceData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.wts_sdk.WtsFlutterApi.onExperienceAvailable$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(experienceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(WtsMessagesPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun onExperienceAction(experienceArg: WtsExperienceData, actionArg: WtsExperienceActionData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.wts_sdk.WtsFlutterApi.onExperienceAction$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(experienceArg, actionArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(WtsMessagesPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface WtsHostApi {
  fun configure(configuration: WtsConfigurationData, callback: (Result<Unit>) -> Unit)
  fun handle(url: String, callback: (Result<WtsDeepLinkData>) -> Unit)
  fun getDeferredDeepLink(callback: (Result<WtsDeepLinkData?>) -> Unit)
  fun setProfileConsent(granted: Boolean, callback: (Result<Unit>) -> Unit)
  fun identify(externalUserId: String, attributes: List<WtsParameterData>, callback: (Result<Unit>) -> Unit)
  fun updateUser(update: WtsUserUpdateData, callback: (Result<Unit>) -> Unit)
  fun setReportedAttribution(attribution: WtsReportedAttributionData, callback: (Result<Unit>) -> Unit)
  fun resetIdentity(callback: (Result<Unit>) -> Unit)
  fun track(eventKey: String, properties: List<WtsParameterData>, revenue: WtsRevenueData?, linkId: String?, callback: (Result<Unit>) -> Unit)
  fun screen(name: String, properties: List<WtsParameterData>, callback: (Result<Unit>) -> Unit)
  fun setExperienceConsent(consent: String, callback: (Result<String>) -> Unit)
  fun presentNextExperience(callback: (Result<Boolean>) -> Unit)
  fun dismissCurrentExperience(callback: (Result<Boolean>) -> Unit)
  fun getExperienceDiagnostics(callback: (Result<WtsExperienceDiagnosticsData>) -> Unit)
  fun flush(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by WtsHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      WtsMessagesPigeonCodec()
    }
    /** Sets up an instance of `WtsHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WtsHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationArg = args[0] as WtsConfigurationData
            api.configure(configurationArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(WtsMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.handle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.handle(urlArg) { result: Result<WtsDeepLinkData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WtsMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.getDeferredDeepLink$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDeferredDeepLink{ result: Result<WtsDeepLinkData?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WtsMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.setProfileConsent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val grantedArg = args[0] as Boolean
            api.setProfileConsent(grantedArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(WtsMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.identify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val externalUserIdArg = args[0] as String
            val attributesArg = args[1] as List<WtsParameterData>
            api.identify(externalUserIdArg, attributesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(WtsMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.updateUser$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val updateArg = args[0] as WtsUserUpdateData
            api.updateUser(updateArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(WtsMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.setReportedAttribution$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val attributionArg = args[0] as WtsReportedAttributionData
            api.setReportedAttribution(attributionArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(WtsMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.resetIdentity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.resetIdentity{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(WtsMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.track$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventKeyArg = args[0] as String
            val propertiesArg = args[1] as List<WtsParameterData>
            val revenueArg = args[2] as WtsRevenueData?
            val linkIdArg = args[3] as String?
            api.track(eventKeyArg, propertiesArg, revenueArg, linkIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(WtsMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.screen$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            val propertiesArg = args[1] as List<WtsParameterData>
            api.screen(nameArg, propertiesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(WtsMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.setExperienceConsent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val consentArg = args[0] as String
            api.setExperienceConsent(consentArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WtsMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.presentNextExperience$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.presentNextExperience{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WtsMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.dismissCurrentExperience$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.dismissCurrentExperience{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WtsMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.getExperienceDiagnostics$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getExperienceDiagnostics{ result: Result<WtsExperienceDiagnosticsData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WtsMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.flush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.flush{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(WtsMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
