// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package co.wetus.sdk.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object WtsMessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class WtsValueKind(val raw: Int) {
  STRING(0),
  NUMBER(1),
  BOOLEAN(2);

  companion object {
    fun ofRaw(raw: Int): WtsValueKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsParameterData (
  val key: String,
  val kind: WtsValueKind,
  val stringValue: String? = null,
  val numberValue: Double? = null,
  val booleanValue: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsParameterData {
      val key = pigeonVar_list[0] as String
      val kind = pigeonVar_list[1] as WtsValueKind
      val stringValue = pigeonVar_list[2] as String?
      val numberValue = pigeonVar_list[3] as Double?
      val booleanValue = pigeonVar_list[4] as Boolean?
      return WtsParameterData(key, kind, stringValue, numberValue, booleanValue)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      key,
      kind,
      stringValue,
      numberValue,
      booleanValue,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsParameterData
    return WtsMessagesPigeonUtils.deepEquals(this.key, other.key) && WtsMessagesPigeonUtils.deepEquals(this.kind, other.kind) && WtsMessagesPigeonUtils.deepEquals(this.stringValue, other.stringValue) && WtsMessagesPigeonUtils.deepEquals(this.numberValue, other.numberValue) && WtsMessagesPigeonUtils.deepEquals(this.booleanValue, other.booleanValue)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.key)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.kind)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.stringValue)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.numberValue)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.booleanValue)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsDeepLinkData (
  val path: String,
  val parameters: List<WtsParameterData>,
  val linkId: String,
  val attributionId: String,
  val isDeferred: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsDeepLinkData {
      val path = pigeonVar_list[0] as String
      val parameters = pigeonVar_list[1] as List<WtsParameterData>
      val linkId = pigeonVar_list[2] as String
      val attributionId = pigeonVar_list[3] as String
      val isDeferred = pigeonVar_list[4] as Boolean
      return WtsDeepLinkData(path, parameters, linkId, attributionId, isDeferred)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      parameters,
      linkId,
      attributionId,
      isDeferred,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsDeepLinkData
    return WtsMessagesPigeonUtils.deepEquals(this.path, other.path) && WtsMessagesPigeonUtils.deepEquals(this.parameters, other.parameters) && WtsMessagesPigeonUtils.deepEquals(this.linkId, other.linkId) && WtsMessagesPigeonUtils.deepEquals(this.attributionId, other.attributionId) && WtsMessagesPigeonUtils.deepEquals(this.isDeferred, other.isDeferred)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.path)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.parameters)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.linkId)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.attributionId)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.isDeferred)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsRevenueData (
  val amount: String,
  val currency: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsRevenueData {
      val amount = pigeonVar_list[0] as String
      val currency = pigeonVar_list[1] as String
      return WtsRevenueData(amount, currency)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      amount,
      currency,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsRevenueData
    return WtsMessagesPigeonUtils.deepEquals(this.amount, other.amount) && WtsMessagesPigeonUtils.deepEquals(this.currency, other.currency)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.amount)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.currency)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WtsConfigurationData (
  val appKey: String,
  val apiBaseUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WtsConfigurationData {
      val appKey = pigeonVar_list[0] as String
      val apiBaseUrl = pigeonVar_list[1] as String?
      return WtsConfigurationData(appKey, apiBaseUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      appKey,
      apiBaseUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WtsConfigurationData
    return WtsMessagesPigeonUtils.deepEquals(this.appKey, other.appKey) && WtsMessagesPigeonUtils.deepEquals(this.apiBaseUrl, other.apiBaseUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.appKey)
    result = 31 * result + WtsMessagesPigeonUtils.deepHash(this.apiBaseUrl)
    return result
  }
}
private open class WtsMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WtsValueKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsParameterData.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsDeepLinkData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsRevenueData.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WtsConfigurationData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is WtsValueKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is WtsParameterData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is WtsDeepLinkData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is WtsRevenueData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is WtsConfigurationData -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface WtsHostApi {
  fun configure(configuration: WtsConfigurationData, callback: (Result<Unit>) -> Unit)
  fun handle(url: String, callback: (Result<WtsDeepLinkData>) -> Unit)
  fun getDeferredDeepLink(callback: (Result<WtsDeepLinkData?>) -> Unit)
  fun track(eventKey: String, properties: List<WtsParameterData>, revenue: WtsRevenueData?, linkId: String?, callback: (Result<Unit>) -> Unit)
  fun flush(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by WtsHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      WtsMessagesPigeonCodec()
    }
    /** Sets up an instance of `WtsHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WtsHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationArg = args[0] as WtsConfigurationData
            api.configure(configurationArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(WtsMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.handle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.handle(urlArg) { result: Result<WtsDeepLinkData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WtsMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.getDeferredDeepLink$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDeferredDeepLink{ result: Result<WtsDeepLinkData?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WtsMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.track$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventKeyArg = args[0] as String
            val propertiesArg = args[1] as List<WtsParameterData>
            val revenueArg = args[2] as WtsRevenueData?
            val linkIdArg = args[3] as String?
            api.track(eventKeyArg, propertiesArg, revenueArg, linkIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(WtsMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wts_sdk.WtsHostApi.flush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.flush{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WtsMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(WtsMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
